### DISCUSSION TITLE
How to compare coverage with base branch?

### DISCUSSION THREAD

**Discussion by adesurirey** [ArtiomTr/jest-coverage-report-action#108] [Q&A]
> Comparing coverage with base branch.

Looks great, how do I activate this? 

I'm currently using `v2.0-rc.2` which works great but I do not have this kind of reports on my PR as on the README screenshot.

**Comment by adesurirey** [comment]
Following my investigation, it looks like I always get commit reports, not full PR reports. I don't know why. 

https://github.com/ArtiomTr/jest-coverage-report-action/blob/a4338fc7969410df56d88a7b043966acc7100590/src/index.ts#L112-L131

I run the action on push and pull_request

```
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
```

![image](https://user-images.githubusercontent.com/22000544/124501054-2854ba00-ddc1-11eb-84f3-21447715e5ac.png)
