### DISCUSSION TITLE
Not run tests multiple times, once on feature branch and once on main branch

### DISCUSSION THREAD

**Discussion by tweaktastic** [ArtiomTr/jest-coverage-report-action#195] [Q&A]
Hi. I wanted to know if there is a way we can disable the test execution two times. I see that we have an option `threshold` that can be used to provide a minimum coverage that is needed for the check to pass. In this case, what would be the reason that the test suite is executed again on the main branch and the reports are compared?
Shouldn't it just execute the suite once, on the feature branch, generate coverage and fail the check if the coverage falls less than this threshold?

**Comment by ArtiomTr** [comment]
Hello @tweaktastic :wave:,

Action runs tests twice because it reports additional information about your coverage (how it has increased / decreased, how new files are covered). It is not possible to disable this feature at this moment.

Could you please clarify why you want to disable these features? Are you complaining about the speed of the action? I look forward to hearing from you.

**Reply by tweaktastic** [reply]
Hi @ArtiomTr ,
Thank you for getting back to me. I understand what you are saying. There might be some details you want to provide in the test runs. My intention is that if we have threshold set in the action configuration, it doesn't make sense to run the tests twice. But I do get your point that you want to provide details on where the coverage would have fallen when compared to `main`?

As for your second point, yes we are concerned about the execution times when running the test suite twice.

**Reply by ArtiomTr** [reply]
@tweaktastic, I see simpler solution, that would improve the performance without loosing any functionality - cache. The action could run tests for base branch only once, then write the results to the cache. Then, on each re-run, it will read cached report, and not run tests for the base branch anymore.

Will this solution help solve your problem?

**Reply by ghost** [reply]
Currently I am solving this by using `actions/upload-artifact` to cache the report from the main branch (develop) and then downloading it in the feature branch.
```
      - name: Upload "develop" covergae report as artifact
        if: github.ref == 'refs/heads/develop'
        uses: actions/upload-artifact@v2
        with:
          name: develop-coverage-report
          path: ./services/app/report.json
          retention-days: 30
          
      - name: Download "develop" coverage report artifact
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
          workflow: unit-test-ui.yml
          name: develop-coverage-report
          path: ./services/app/develop-coverage-report/
          search_artifacts: true
```
Would it make sense to integrate something like this inside the action?
