### DISCUSSION TITLE
Get coverage from base branch

### DISCUSSION THREAD

**Discussion by patrickacioli** [ArtiomTr/jest-coverage-report-action#205] [Q&A]
I really confused about how to generate a branch diff when running test-script. I setup following action, but, the response doesn't includes the diff.

```
name: Jest Coverage
on: ["push"]

jobs:
  base-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: User Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          path: base
          ref: ${{ github.base_ref }}

      - name: Run base coverage
        run: npx jest --silent --ci --testLocationInResults --colors --coverage --json --outputFile=base-report.json --coverageReporters="text" --coverageReporters="text-summary" --forceExit
            
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: base-report.json

  head-coverage:
    runs-on: ubuntu-latest
    needs:
      - base-coverage
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: User Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: none
          base-coverage-file: base-report.json
          test-script: npx jest --silent --ci --testLocationInResults --colors --coverage --json --outputFile=report.json --coverageReporters="text" --coverageReporters="text-summary" --forceExit
```

![image](https://user-images.githubusercontent.com/6707011/145248327-45b241a6-6a68-444d-bdf9-8a1efac044b6.png)

**Comment by patrickacioli** [comment]
I update my action for following:

```
name: Jest Coverage
on: ["push"]

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: User Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

And still without diff report. See follow:

```
PASS src/api/security/auth.service.spec.ts
PASS src/db/prisma.service.spec.ts

Test Suites: 6 passed, 6 total
Tests:       34 passed, 34 total
Snapshots:   0 total
Time:        12.921 s
Ran all test suites.
Test results written to: report.json
Running tests ended
Begin collecting coverage...
Collecting coverage ended
Begin parsing coverage...
Parsing coverage ended
Head coverage collection ended
Begin switching to base branch...   # Skipped?
Switching to base branch skipped  #
Switching to base branch ended     #
Begin base coverage collection...
Base coverage collection skipped
Base coverage collection ended
Begin generating report...
Generating report ended
Begin report publish...
Report publish ended
Begin failed tests' annotations publication...
Failed tests' annotations publication skipped
Failed tests' annotations publication ended
Begin coverage annotations publication...
Coverage annotations publication ended
```


What's the reason of skipping stages?
