### DISCUSSION TITLE
Monorepo or yarnWorkspaces support?

### DISCUSSION THREAD

**Discussion by marexandre** [ArtiomTr/jest-coverage-report-action#260] [Q&A] [answered]
Is it possible to use this Github action with a monorepo or [yarn workspaces](https://classic.yarnpkg.com/lang/en/docs/workspaces/) setup?

For example if I have two following folders in a monorepo 
- '/apps/*'
- '/packages/*'

Both of this using Jest, but in apps folder there could be Nextjs/express etc applications, and in packages folder there could be shared helpers/utilities and shared React components, so each app or packages can have separate Jest config/setup.

Wondering if there is a way to use this github action to get coverage posted to a PR. Guessing if I manually add one entry per app/package it might be possible, but wondering if there could be a way to pull in `"workspaces" : ["apps/*", "packages/*"]` from `package.json` and run Jest coverage agains all subfolders and post a total coverage or/and for individual app/package separately.

**Comment by ArtiomTr** [comment, marked as answer]
Hello @marexandre :wave:,

Yes, it is possible to run this action on yarn workspaces setup. You can simply run action for each package separately:
```yml
name: CI
on:
    pull_request:
        branches: [main]
jobs:
    coverage:
        name: Coverage report
        runs-on: ubuntu-latest
        strategy:
            matrix:
                path: 
                    - ./packages/first
                    - ./packages/second
                    - ./apps/main
                    - ./apps/other
        steps:
            - uses: actions/checkout@v1

            - name: Use Node 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install npm 17.x
              run: npm i -g npm@latest

            - name: Installing dependencies
              run: npm install

            - uses: artiomtr/jest-coverage-report-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  skip-step: install
                  working-directory: ${{ matrix.path }}
                  test-script: yarn jest
```

But, this will require adding dependencies manually. So I recommend checking out [get-changed-workspaces](https://github.com/AlexShukel/get-changed-workspaces-action) action. This action will help you to run actions only for changed packages. For instance, this is the configuration for one of my projects:
```yml
name: CI
on:
    pull_request:
        branches: [main]
    workflow_dispatch:
jobs:
    generate_matrix:
        name: Get changed packages
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        outputs:
            names: ${{ steps.changed_packages.outputs.names }}
            paths: ${{ steps.changed_packages.outputs.paths }}
            empty: ${{ steps.changed_packages.outputs.empty }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Find changed packages
              id: changed_packages
              uses: alexshukel/get-changed-workspaces-action@v1.0.0
    coverage:
        name: Coverage report
        if: ${{ !fromJson(needs.generate_matrix.outputs.empty) }}
        needs: [generate_matrix]
        runs-on: ubuntu-latest
        strategy:
            matrix:
                path: ${{ fromJson(needs.generate_matrix.outputs.paths) }}
        steps:
            - uses: actions/checkout@v1

            - name: Use Node 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install npm 17.x
              run: npm i -g npm@latest

            - name: Installing dependencies
              run: npm install

            - uses: artiomtr/jest-coverage-report-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  skip-step: install
                  working-directory: ${{ matrix.path }}
                  test-script: npm run test:coverage # change to your test script
```
