### DISCUSSION TITLE
Duplicate running of tests

### DISCUSSION THREAD

**Discussion by stretch0** [ArtiomTr/jest-coverage-report-action#300] [Q&A] [answered]
Running the following in my CI appears to trigger each test to be run twice.

```yaml
- name: Run unit tests
        uses: ArtiomTr/jest-coverage-report-action@v2
```

It runs the tests in my current branch and then appears to checkout master / main and run the tests again

```
Begin initialization stage...
Initialization stage ended
Begin stages.parsethreshold...
stages.parseThreshold ended
Begin head coverage collection...
Begin installing dependencies...
/opt/hostedtoolcache/node/16.16.0/x64/bin/npm install
Installing dependencies ended
Begin running tests...
/opt/hostedtoolcache/node/16.16.0/x64/bin/npx jest --ci --json --coverage --testLocationInResults --outputFile=report.json

... runs tests

/usr/bin/git checkout -f master
Switched to a new branch 'master'
branch 'master' set up to track 'origin/master'.
/opt/hostedtoolcache/node/16.16.0/x64/bin/npm install
Installing dependencies ended
Begin running tests...
/opt/hostedtoolcache/node/16.16.0/x64/bin/npx jest --ci --json --coverage --testLocationInResults --outputFile=report.json

... runs tests again
```

Is this so it can generate a diff between master and current branch and say what's changed?

Is this necessary? Is there a way to disable this? 

It is doubling the time it takes for our unit tests to run and wondering if it can just get a report from our master branch wihtout having to run it every time.

**Comment by ArtiomTr** [comment, marked as answer]
Hello @stretch0 :wave:,

Yes, that is the default behaviour. The instructions to disable it are described in the [readme](https://github.com/ArtiomTr/jest-coverage-report-action#opt-out-coverage-comparison-features) file.

**Reply by stretch0** [reply]
@ArtiomTr That makes sense, thank you.

Does `[jest-coverage-report-action](https://github.com/ArtiomTr/jest-coverage-report-action)` provide a way of writing the coverage report each time or do I need to add a custom test-script to tell jest to write it?

Something like this:

```
with:
    test-script: npm run test -- --coverage // and somehow commit to my PR
```

**Reply by ArtiomTr** [reply]
@stretch0, you should not commit your report file, just collect it on the previous step of your workflow:

```yml
# ...

    - name: Collect report
      run: npx jest --ci --json --coverage --testLocationInResults --outputFile=report.json

    - uses: ArtiomTr/jest-coverage-report-action@v2
      with:
          coverage-file: report.json
          base-coverage-file: report.json
```
