### DISCUSSION TITLE
Error: report not being printed and action failing

### DISCUSSION THREAD

**Discussion by egimenos** [ArtiomTr/jest-coverage-report-action#323] [Q&A] [answered]
Hi, not sure what is happening. The action is failing but I can't extract any valuable error message. Basically the output table is not being printed in the comment and the actions fails although the test suite passes.

The action was working fine for previous PR's until this one. I thought it was caused because this is the first one where the coverage threshold is not met, but we lowered the threshold just to check and is still failing.

My action:

```yml
name: CI Pipeline Node

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-unit-tests-with-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checks-out repository under $GITHUB_WORKSPACE, so workflow can access it
        uses: actions/checkout@v3
      - name: Read package json to extract node version
        id: read_package_json
        uses: ./shared-gh-actions/actions/read-json@v1.0.0
        with:
          path: ./package.json
      - name: Setup node -> download and cache node and add it to the PATH, cache yarn dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '${{ fromJson(steps.read_package_json.outputs.file).engines.node }}'
          cache: 'yarn'
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          package-manager: yarn
          output: report-markdown
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}
```
The generic error:

```sh
Error: The process '/opt/hostedtoolcache/node/16.17.1/x64/bin/npx' failed with exit code 1
Error: The process '/opt/hostedtoolcache/node/16.17.1/x64/bin/npx' failed with exit code 1
    at th._setResult (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:21:17898)
    at th.CheckComplete (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:21:17485)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:21:16477)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```
Some pictures of what I guess are the relevant parts of the logs:

First it shows this error but the action keeps running. The test suite passes.

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/18742365/197500261-08b9a754-b58c-44e5-8a9b-9efc909bad72.png">

And then it finally outputs this:

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/18742365/197500665-254e99c8-91b1-4031-a832-69359e27fea2.png">

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/18742365/197500889-7c512169-ac8f-4cc0-98f9-77772363529c.png">

And finallly this. Here it says the test suite fails, but is not really the case as you can see in above pictures:

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/18742365/197501150-a66d3fe2-63bc-428c-8243-36a729825d60.png">

**Comment by ArtiomTr** [comment, marked as answer]
Hello @egimenos :wave:,

Could you please attach a log archive here? It looks like jest hasn't exited successfully, possibly caused by a memory leak in asynchronous tests - when you start a promise and then forget to await it. That's how you can download the log archive:
![image](https://user-images.githubusercontent.com/44021713/197525528-11d9db8e-9a92-4ac0-9758-59a3f43b29de.png)

UPDATE: In case anyone is facing the same issue, here is a [link to the comment thread](https://github.com/ArtiomTr/jest-coverage-report-action/discussions/323#discussioncomment-3952118), about how to fix these issues.

**Reply by egimenos** [reply]
I can only mark as answer this one, but the fixed action can be find in the comments below.

**Comment by egimenos** [comment]
Hi @ArtiomTr , there it is, let me know if you need anything else.

Thanks in advance!

**Reply by ArtiomTr** [reply]
Yeah, that's actually a thresholds failure
![image](https://user-images.githubusercontent.com/44021713/197559162-e6bcfc86-c66d-46bf-b035-312ba54f2ded.png)
The action algorithm on displaying threshold failures is very poor at this moment, so you're seeing an unknown error. I'm already working on improving it, sorry for strange action behavior.

**Reply by ArtiomTr** [reply]
Also, just saw that you're installing dependencies before running this action - action automatically installs dependencies, so you're installing them twice. To skip dependency installation for this action, just add option `skip-step: install`, like this:
```yaml
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          package-manager: yarn
          output: report-markdown
          skip-step: install
```
This will speed up action a little :)

**Reply by egimenos** [reply]
But still it should print the output report coverage right? 
Edit: Thanks for the tip by the way, i'm new to actions so any tip is super appreciated!

**Reply by ArtiomTr** [reply]
Not sure how `sticky-pull-request-comment` works, I think that you can remove that step, and skip `output` option - that should work nicely:
```yaml
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          package-manager: yarn
          # output: report-markdown - delete this option
          skip-step: install
#       Also, delete this step:
#     - uses: marocchino/sticky-pull-request-comment@v2
#       with:
#         message: ${{ steps.coverage.outputs.report }}
```

**Reply by ArtiomTr** [reply]
To clarify, my recommendation would be to change the action to the following:
```yaml
name: CI Pipeline Node

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-unit-tests-with-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checks-out repository under $GITHUB_WORKSPACE, so workflow can access it
        uses: actions/checkout@v3
      - name: Read package json to extract node version
        id: read_package_json
        uses: ./shared-gh-actions/actions/read-json@v1.0.0
        with:
          path: ./package.json
      - name: Setup node -> download and cache node and add it to the PATH, cache yarn dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '${{ fromJson(steps.read_package_json.outputs.file).engines.node }}'
          cache: 'yarn'
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          package-manager: yarn
          skip-step: install
```
