### DISCUSSION TITLE
Customize plugin comment title

### DISCUSSION THREAD

**Discussion by joehoppe** [ArtiomTr/jest-coverage-report-action#357] [Q&A] [answered]
My GitHub Actions dev YAML pipeline runs two npm scripts
1. test-coverage
2. integration-test-coverage

Both use this plugin to display the code coverage report on the pull request

But both add a comment "Coverage report", and I'm not able to tell which is which

Is the comment that the plugin generates customizable?

**Comment by ArtiomTr** [comment, marked as answer]
Hello @joehoppe :wave:,

Sorry, this feature is not documented, but there is an option to customize the comment title:
https://github.com/ArtiomTr/jest-coverage-report-action/blob/952a05968ad9e0b4ab2ab221a8d7d72e621aec51/action.yml#L38-L40
For example, this could be:
```yaml
name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                  custom-title: Integration test coverage 
```
