### DISCUSSION TITLE
Annotation not being logged in the Coverage annotations (🧪 jest-coverage-report-action) tab

### DISCUSSION THREAD

**Discussion by LegendSebastiano-L** [ArtiomTr/jest-coverage-report-action#365] [Q&A]
not sure why but at some point it stopped creating annotations in the Coverage annotations (🧪 jest-coverage-report-action) tab
![image](https://user-images.githubusercontent.com/61748264/234523430-8c71f241-58df-48e0-815d-3a570d052792.png)

This is my config:
```
      - name: Find PR Number for coverage report message
        uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: Show coverage differences
        uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
          test-script: yarn test:coverage:pipeline
          skip-step: all
          coverage-file: ${{ env.BRANCH_COVERAGE_FILE_LOCATION }}
          base-coverage-file: ./${{ env.S3_BASE_COVERAGE_FILE_KEY }}
          output: comment, report-markdown
          prnumber: ${{ steps.findPr.outputs.number }}
```
