### DISCUSSION TITLE
Pass environment variables into the action script

### DISCUSSION THREAD

**Discussion by victor-shelepen** [ArtiomTr/jest-coverage-report-action#379] [Q&A]
There is integration testing with other services. There is a need to pass environment variables to the testing script. I've not found such functionality in your documentation. Could you help me?
Regards, Victor.

**Comment by ArtiomTr** [comment]
Hello @victor-shelepen :wave:,

I haven't tested it, but I think it should work the same way, as for ordinary GitHub workflow:
```yaml
name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              env:
                  API_KEY: 123456
```

Let me know, if it works. Also, more documentation could be found here: https://docs.github.com/en/actions/learn-github-actions/variables

**Reply by victor-shelepen** [reply]
Your suggestion is logical I thought about it. But it is the action and it does not support to not disrupt the inside behavior. Your approach is absent in the documentation. At first, I override the plugin configuration
```yaml
test-script: VAR_1=A npm test
```
But There were too many parameters. Now I generate .env inside and use the library ```dotenv``` to load the configuration.
```yaml
- name: Environment
  env:
    testScript: |
      FIREBASE_SERVICE_ACCOUNT_BASE64=${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
      ...
  run: echo "${{env.testScript}}" > .env
```
