### DISCUSSION TITLE
Jest coverage is always zero, despite all tests passing

### DISCUSSION THREAD

**Discussion by vg-matas** [ArtiomTr/jest-coverage-report-action#391] [Q&A]
I see this output for my test step. All tests are passing but jest thinks coverage is zero.
```
Run yarn test --ci --json --coverage --testLocationInResults --outputFile=report.json
PASS services/public-api/tests/RequestBuilder.test.ts (5.279 s)
  RequestBuilder
    ✓ should build request for GET request (13 ms)
    // Many more tests with ✓

-------------------------------------|---------|----------|---------|---------|-------------------
File                                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-------------------------------------|---------|----------|---------|---------|-------------------
  RequestBuilder.ts                  |       0 |        0 |       0 |       0 | 1-100             
-------------------------------------|---------|----------|---------|---------|-------------------
// Removed other lines for sake of simplicity

================================================================================
Jest: "global" coverage threshold for statements (80%) not met: 0%
Jest: "global" coverage threshold for branches (80%) not met: 0%
Jest: "global" coverage threshold for lines (80%) not met: 0%
Jest: "global" coverage threshold for functions (80%) not met: 0%
```

When I run same command on my laptop I can see real results like

```
$ yarn test --ci --json --coverage --testLocationInResults --outputFile=report.json

-------------------------------------|---------|----------|---------|---------|--------------------------------------
File                                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                    
-------------------------------------|---------|----------|---------|---------|--------------------------------------               
  RequestBuilder.ts                  |     100 |    93.33 |     100 |     100 | 94-96        
```

My job definitions are like this. All steps before "Test" succeeds

```
jobs:
  build:
    name: Analyze Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: |
          corepack enable
          corepack prepare yarn@3.5.1  --activate
          yarn --version

      - name: Install
        uses: ./.github/actions/yarn-nm-install

      - name: Build
        run: yarn build

      - name: Prettier Check
        run: yarn prettier-check

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --json --coverage --testLocationInResults --outputFile=report.json
```

I tried different commands, but none worked

```
yarn test --ci --json --coverage --testLocationInResults --outputFile=report.json
npx jest --ci --json --coverage --testLocationInResults --outputFile=report.json
npx jest
yarn jest
```

I'm not sure what I'm doing wrong but I'd appreciate any help.
