### DISCUSSION TITLE
Which steps need to be taken to support private repos?

### DISCUSSION THREAD

**Discussion by pixelass** [ArtiomTr/jest-coverage-report-action#399] [Q&A]
## Question

1. Is this compatible with private repos?
2. Which steps need to be taken?
3. Is there an example workflow?

## Steps taken:

**On `main`**

Provide a workflow with the suggested `pull_request_target`

```yml
name: Unit Tests
on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  jest:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: run jest
        run: npm run test:jest
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: jest-report
          path: coverage/
          retention-days: 1
      - uses: ArtiomTr/jest-coverage-report-action@v2
```

We also tried this:

```yml
name: Unit Tests
on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  jest:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: run jest
        run: npm run test:jest
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: jest-report
          path: coverage/
          retention-days: 1
  jest-reporter:
    needs: jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - uses: actions/download-artifact@v2
        with:
          name: jest-report
          path: coverage/
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: coverage/coverage-final.json
          base-coverage-file: coverage/coverage-final.json
```

where our jest config contains this

```json5
{
	collectCoverage: true,
	coverageDirectory: "./coverage",
	coverageProvider: "v8",
	coverageReporters: ["lcov", "text", "json"],
	coverageThreshold: { // Attempt to fix the "Cannot convert undefined or null to object" issue
		global: {
			lines: 80,
		},
	}
}
```

**coverage folder**

![image](https://github.com/ArtiomTr/jest-coverage-report-action/assets/1148334/9cc78325-97ef-4cf9-b663-de2c821fec46)

The following error happens on main and on pull requests based on the lates main (which has the workflow file as suggested)

## Error Log

```
Begin collecting coverage...
Loading code coverage from file: coverage/coverage-final.json
Collecting coverage ended
Begin parsing coverage...
Parsing coverage ended
Base coverage collection ended
Begin switching back to original branch...
Not checked out to the original branch - failed to get it.
Switching back to original branch skipped
Switching back to original branch ended
Begin stages.checkthreshold...
stages.checkThreshold failed
Error: TypeError: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Cd (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:2197:3201)
    at Z9 (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:2197:3[64](https://github.com/storydocks/framily-ai/actions/runs/6517185484/job/17701432012#step:6:66)5)
    at /home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:2230:15551
    at ei (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:2221:164)
    at UD (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:2230:15505)
stages.checkThreshold ended
```

After adjusting based on exisiting issues we got this error

```
Begin collecting coverage...
Loading code coverage from file: coverage/report.json
Not checked out to the original branch - failed to get it.
Collecting coverage failed
Error: Coverage output file not found. (file "coverage/report.json" not found)
Error: Coverage output file not found. (file "coverage/report.json" not found)
    at F7 (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:2220:340)
    at async ei (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:2221:158)
    at async Py (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:2221:633)
    at async /home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:2230:1[49](https://github.com/storydocks/framily-ai/actions/runs/6517230793/job/17701518456#step:6:51)95
    at async ei (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:2221:1[58](https://github.com/storydocks/framily-ai/actions/runs/6517230793/job/17701518456#step:6:60))
    at async UD (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:2230:14931)
Collecting coverage ended
```

for this adjustment: (from here https://github.com/ArtiomTr/jest-coverage-report-action/issues/388#issuecomment-1651712951)

```yml
name: Unit Tests
on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  jest:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: run jest
        run: npx jest --ci --json --coverage --testLocationInResults --outputFile=report.json
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: coverage/report.json
          base-coverage-file: coverage/report.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 90
          annotations: coverage
```
## Conclusion

It is unclear if or if or how this works in private repos, which steps are actually necessary and what might cause this error. 
The docs are very vague and each adjustment leads to different errors which lead down a rabbit hole.  
Frankly we decided to remove this action as it is not clear if this even works with our setup
