### DISCUSSION TITLE
Comparing with master branch doesn't work

### DISCUSSION THREAD

**Discussion by berksafran-wt** [ArtiomTr/jest-coverage-report-action#426] [Q&A]
Hello, 

I could not run the comparison feature with the master branch no matter what I did. I share the necessary pipeline information and logs below.

**Logs**
```
...
Test Suites: 52 passed, 52 total
Tests:       389 passed, 389 total
Snapshots:   0 total
Time:        19.698 s
Test results written to: report.json
Done in 20.35s.
Running tests ended
Begin collecting coverage...
Loading code coverage from file: report.json
Collecting coverage ended
Begin parsing coverage...
Parsing coverage ended
Head coverage collection ended
Begin switching to base branch...
Switching to base branch skipped
Switching to base branch ended
Begin base coverage collection...
Base coverage collection skipped
Base coverage collection ended
Begin switching back to original branch...
Not checked out to the original branch - failed to get it.
Switching back to original branch skipped
Switching back to original branch ended
Begin stages.checkthreshold...
stages.checkThreshold ended
Begin generating report...
Generating report ended
Begin report publish...
Report publish skipped
Report publish ended
Begin setting outputs...
Setting outputs ended
Begin failed tests' annotations publication...
Failed tests' annotations publication ended
Begin coverage annotations publication...
Coverage annotations publication skipped
Coverage annotations publication ended
```

**Pipeline config**
```
name: javascript-test
on:
  pull_request_target: 
    branches:
      - master
  workflow_call:
    inputs:
      node_version:
        description: 'Node version for docker image'
        required: false
        type: string
        default: '16'
permissions:
  checks: write
  pull-requests: write
  contents: write
jobs:
  javascript-test:
    runs-on: [ ubuntu-latest ]
    container:
      image: node:${{ inputs.node_version }}
    env:
      NODE_ENV: test
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/cache@v4.0.2
      with:
        path: "./node_modules"
        key: "${{ runner.os }}-${{ hashFiles('yarn.lock') }}"
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
    - uses: ArtiomTr/jest-coverage-report-action@v2.3.0
      id: coverage
      with:
        skip-step: none
        github-token: ${{ secrets.GITHUB_TOKEN }}
        package-manager: yarn
        icons: emoji
        test-script: yarn test --ci --json ----testLocationInResults --outputFile=report.json
        output: report-markdown
    - uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ steps.findPr.outputs.number }}
        message: ${{ steps.coverage.outputs.report }}
```

**Expected**

The comparison feature with showing new unit test files like the following screenshot

![image](https://github.com/ArtiomTr/jest-coverage-report-action/assets/166023899/a71070a3-2e88-48e7-8078-a157ec57fd98)

Thanks.
