### ISSUE TITLE
Cannot make it work with skip-step:all 

### ISSUE THREAD

**Issue by adesurirey** [ArtiomTr/jest-coverage-report-action#105]
It seems that the action cannot access coverage report when skipping all, this is the output: 

```
Could not read report file located at report.json [Error: ENOENT: no such file or directory, open 'report.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'report.json'
}
```

My config: 
```
name: Main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn bootstrap
      - name: Run tests
        run: yarn test-ci
      - name: Extract code coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: all
          threshold: 80
          package-manager: yarn
          annotations: coverage
```

```
"test-ci": "yarn jest --ci --coverage --coverageReporters=\"text\" --coverageReporters=\"text-summary\"",
```
