### ISSUE TITLE
Problems running only collect coverage

### ISSUE THREAD

**Issue by gabiwassan** [ArtiomTr/jest-coverage-report-action#113]
Hi,
I'm trying to use our action just to collect my report and comment on github that information, but I can't run successfully.

My action:
```
      - name: Step 08 - Run Tests & Collect Coverage
        run: |
          echo “PATH_WAZUH-APP=$GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/” >> $GITHUB_ENV
          cd ./kibana/plugins/wazuh-kibana-app
          ls -la
          echo $GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/
          yarn run test:jest --silent --ci --testLocationInResults --colors --coverage --json --outputFile=report.json

      - name: Step 09 - Comment coverage
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
          working-directory: ${{ env.PATH_WAZUH-APP }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: all
```

Error result:
```
Run artiomtr/jest-coverage-report-action@v2.0-rc.1
  with:
    github-token: ***
    skip-step: all
    test-script: npx jest --silent --ci --coverage --testLocationInResults --json --outputFile="report.json"
    icons: emoji
    annotations: all
    package-manager: npm
  env:
    “PATH_WAZUH-APP: /home/runner/work/wazuh-kibana-app/wazuh-kibana-app/kibana/plugins/wazuh-kibana-app/”
Could not read report file located at report.json [Error: ENOENT: no such file or directory, open 'report.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'report.json'
}
/usr/bin/git fetch --all --depth=1
fatal: not a git repository (or any of the parent directories): .git
Error fetching git repository Error: The process '/usr/bin/git' failed with exit code 128
    at f._setResult (/home/runner/work/_actions/artiomtr/jest-coverage-report-action/v2.0-rc.1/dist/index.js:2:11470)
    at f.CheckComplete (/home/runner/work/_actions/artiomtr/jest-coverage-report-action/v2.0-rc.1/dist/index.js:2:10900)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/artiomtr/jest-coverage-report-action/v2.0-rc.1/dist/index.js:2:9944)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
/usr/bin/git checkout -f 4.3-7.10
fatal: not a git repository (or any of the parent directories): .git
Error: The process '/usr/bin/git' failed with exit code 128


```

Here [my action.yml](https://github.com/wazuh/wazuh-kibana-app/blob/f5e2a9069cdba7288c86e70140fc36bb1cd6ab59/.github/workflows/wazuh-unit-test.yml)

**Comment by ArtiomTr** [comment]
Hello @gabiwassan! 👋

Sorry for the late reply. As far as I can see, in your configuration the `working-directory` has correct value, but it is not being passed to the action. I'm not sure, but it seems to me that the issue is with the name of the variable: try to rename it so that no hyphen is used (for example `PATH_WAZUH_APP`). If that doesn't work, try running an action with a configuration like this:

```yml
      - name: Step 08 - Run Tests & Collect Coverage
        run: |
          echo “PATH_WAZUH-APP=$GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/” >> $GITHUB_ENV
          cd ./kibana/plugins/wazuh-kibana-app
          ls -la
          echo $GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/
          yarn run test:jest --silent --ci --testLocationInResults --colors --coverage --json --outputFile=report.json

      - name: Step 09 - Comment coverage
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
#       here is the change    ↓
          working-directory: kibana/plugins/wazuh-kibana-app/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: all
```

Hope my answer will help you!

**Comment by ig-onoffice-de** [comment]
I have the same problem. working-directory is given as literal
`working-directory: frontend`
But getting error
`Could not read report file located at frontend/report.json [Error: ENOENT: no such file or directory, open 'frontend/report.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'frontend/report.json'
}`
Also tried  `working-directory: ./frontend` and `working-directory: frontend/` which should be the same.

**Comment by ArtiomTr** [comment]
Hello @ig-onoffice-de,

Could you send me the full `action.yml` file as well as a screenshot of the console output of the action? Thanks in advance.

**Comment by gabiwassan** [comment]
> Hello @gabiwassan! 
> 
> Sorry for the late reply. As far as I can see, in your configuration the `working-directory` has correct value, but it is not being passed to the action. I'm not sure, but it seems to me that the issue is with the name of the variable: try to rename it so that no hyphen is used (for example `PATH_WAZUH_APP`). If that doesn't work, try running an action with a configuration like this:
> 
> ```yaml
>       - name: Step 08 - Run Tests & Collect Coverage
>         run: |
>           echo “PATH_WAZUH-APP=$GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/” >> $GITHUB_ENV
>           cd ./kibana/plugins/wazuh-kibana-app
>           ls -la
>           echo $GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/
>           yarn run test:jest --silent --ci --testLocationInResults --colors --coverage --json --outputFile=report.json
> 
>       - name: Step 09 - Comment coverage
>         uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
>         with:
> #       here is the change    ↓
>           working-directory: kibana/plugins/wazuh-kibana-app/
>           github-token: ${{ secrets.GITHUB_TOKEN }}
>           skip-step: all
> ```
> 
> Hope my answer will help you!

Hi @ArtiomTr, don't apologize, it's okay 😃 
I tried with this configuration, but if it keeps generating the same error: 
```
fatal: not a git repository (or any of the parent directories): .git
Error fetching git repository Error: The process '/usr/bin/git' failed with exit code 128
    at f._setResult (/home/runner/work/_actions/artiomtr/jest-coverage-report-action/v2.0-rc.1/dist/index.js:2:11470)
    at f.CheckComplete (/home/runner/work/_actions/artiomtr/jest-coverage-report-action/v2.0-rc.1/dist/index.js:2:10900)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/artiomtr/jest-coverage-report-action/v2.0-rc.1/dist/index.js:2:9944)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
/usr/bin/git checkout -f 4.3-7.10
fatal: not a git repository (or any of the parent directories): .git
Error: The process '/usr/bin/git' failed with exit code 128
```

**Comment by ArtiomTr** [comment]
@gabiwassan, could you please send the action arguments as you did in your first comment? Like this:

> Error result:
> 
> ```
> Run artiomtr/jest-coverage-report-action@v2.0-rc.1
>   with:
>     github-token: ***
>     skip-step: all
>     test-script: npx jest --silent --ci --coverage --testLocationInResults --json --outputFile="report.json"
>     icons: emoji
>     annotations: all
>     package-manager: npm
>   env:
>     “PATH_WAZUH-APP: /home/runner/work/wazuh-kibana-app/wazuh-kibana-app/kibana/plugins/wazuh-kibana-app/”
> Could not read report file located at report.json [Error: ENOENT: no such file or directory, open 'report.json'] {

Also, could you try please to set up working-directory variable as shown below:

```yml
          working-directory: /home/runner/work/wazuh-kibana-app/wazuh-kibana-app/kibana/plugins/wazuh-kibana-app/
```

**Comment by gabiwassan** [comment]
@ArtiomTr [here](https://github.com/wazuh/wazuh-kibana-app/blob/9d70824b0ec473e1909a5bfd080c3a973214d3f5/.github/workflows/wazuh-unit-test.yml) the action.yml 
Y try with this: `working-directory: /home/runner/work/wazuh-kibana-app/wazuh-kibana-app/kibana/plugins/wazuh-kibana-app/
` but i had the same error.

**Comment by ArtiomTr** [comment]
@gabiwassan,

I think that the problem is that you're changing directory in previous step, to collect coverage. You can try to simply remove `working-directory` option from your `action.yml` file, or just to exit working directory in previous step. So possible configurations could be:
1. Remove working directory:
```yml
      - name: Step 08 - Run Tests & Collect Coverage
        run: |
          echo “PATH_WAZUH-APP=$GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/” >> $GITHUB_ENV
          cd ./kibana/plugins/wazuh-kibana-app
          ls -la
          echo $GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/
          yarn run test:jest --silent --ci --testLocationInResults --colors --coverage --json --outputFile=report.json

      - name: Step 09 - Comment coverage
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
#         working-directory: ./kibana/plugins/wazuh-kibana-app/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: all
```
2. Exit in previous step:
```yml
      - name: Step 08 - Run Tests & Collect Coverage
        run: |
          echo “PATH_WAZUH-APP=$GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/” >> $GITHUB_ENV
          cd ./kibana/plugins/wazuh-kibana-app
          ls -la
          echo $GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/
          yarn run test:jest --silent --ci --testLocationInResults --colors --coverage --json --outputFile=report.json
#             ↓
          cd ../../..

      - name: Step 09 - Comment coverage
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
# and specify working directory ↓
          working-directory: ./kibana/plugins/wazuh-kibana-app/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: all
```

If these solutions do not help you, then wait until #118 is merged into the master.
