### ISSUE TITLE
Custom test script error: command "jest" not found

### ISSUE THREAD

**Issue by adesurirey** [ArtiomTr/jest-coverage-report-action#115]
Hello, I can't make my custom script working. 

It looks like the dev dependencies are not installed. But before switching to this config I was running `yarn jest` in my own step (using `skip-step: all`) and it was working ok. 

Action logs:
```console
Run ArtiomTr/jest-coverage-report-action@v2.0-rc.2
/usr/local/bin/yarn test-ci:coverage
yarn run v1.22.10
$ yarn jest --silent --ci --coverage --testLocationInResults --json --outputFile="report.json"
error Command "jest" not found. Did you mean "test"?
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Test execution failed with error: Error: The process '/usr/local/bin/yarn' failed with exit code 1
    at f._setResult (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0-rc.2/dist/index.js:2:11470)
    at f.CheckComplete (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0-rc.2/dist/index.js:2:10900)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0-rc.2/dist/index.js:2:9944)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Could not read report file located at report.json [Error: ENOENT: no such file or directory, open 'report.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'report.json'
}
```

The job: 
```yml
test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn bootstrap
      - name: Run tests
        uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.2
        with:
          test-script: yarn test-ci:coverage
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: install
```
