### ISSUE TITLE
Action fails when using `replaceAll` in codebase

### ISSUE THREAD

**Issue by ShayDavidson** [ArtiomTr/jest-coverage-report-action#122]
Hello! We're getting a `.replaceAll is not a function` error when running this action on codebase that contains `.replaceAll` (assuming due to an older Node version). 

Even after trying to specify the node version via:
```
strategy:
  matrix:
    node-version: [15.x]
```

The error still occurs.

Anything we're missing config wise?
Thanks

**Comment by ArtiomTr** [comment]
Hello @ShayDavidson,

The problem is that the action runs your tests in its own environment, where the node version is "12.x". I will upgrade the node now, but I will not close this issue as I will try to find a more flexible solution to this problem.

**Comment by ArtiomTr** [comment]
I tried to update the version of the node, but I found out that I could not raise it higher than `12.x`. However, I suddenly found a more flexible solution to this problem - now the action is launched not in its own environment, but in the environment that you provide to it. This means that now, you can simply call `actions/setup-node`, set the node to the version you want, and use the action!

**Comment by ShayDavidson** [comment]
Thanks @ArtiomTr!

For some reason it's still not working. Posting here our workflow in-case you have a wild idea:

```
jobs:
  pr-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v1
      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```
