### ISSUE TITLE
Could not read report file located at report.json

### ISSUE THREAD

**Issue by MatejSandor** [ArtiomTr/jest-coverage-report-action#127]
Hello @ArtiomTr , I tried to use the Jest github-action as it is in the instructions. However, I get the following error every time. Can you please tell me what's going wrong here?

Github Actions Configuration:
```yaml
name: 'coverage'
on:
    pull_request:
        branches:
            - master
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: artiomtr/jest-coverage-report-action@v2.0-rc.2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  package-manager: yarn
                  test-script: yarn run test -- --silent --ci --coverage --coverageReporters="text" --coverageReporters="text-summary"
                  #   threshold: 80 
```

Github Action Error Screenshot: 
![image](https://user-images.githubusercontent.com/34487810/128868573-a7b17701-21bf-40dd-8ceb-25874dd0be5e.png)

I can't seem to figure out what might be the issue. The tests as you can see are completed correctly the final step just fails which causes the entire action to fail even though all tests have passed. Originally I had just yarn run test in the test-script as that is what I would use normally but that doesn't work either
