### ISSUE TITLE
Option to add failed tests as comment

### ISSUE THREAD

**Issue by sidharthv96** [ArtiomTr/jest-coverage-report-action#133]
When PRs are huge, finding annotations is a chore.
If a summary of failed tests are added as a comment like coverage, it would be much easier to review.

I can raise the PR if the feature can be added.

**Comment by sidharthv96** [comment]
Is this coming in the Refactor branch? 
Saw that you are using errors in the body of the comment in that branch.

**Comment by ArtiomTr** [comment]
Hello @sidharthv96 👋
Refactor branch does not bring new functionality, it only introduces new approach how to run collection phases. The errors you saw are problems collected in some stages, so if the action fails, it will print all the execution logs.

Thank you for the feature request! I will be glad if you want to take part in the development of this action.

**Comment by sidharthv96** [comment]
Okay, So I'll start my PR based on the Refactor branch if that's in a working condition.
Also, how are you testing the action during development? I'm not very familiar with the workflow of writing actions.

**Comment by ArtiomTr** [comment]
You can check your PR in a dummy repository like this -> [jest-coverage-report-action-test](https://github.com/ArtiomTr/jest-coverage-report-action-test). Then, in your `action.yml` file specify configuration like this one:
```yml
name: 'coverage'
on:
    pull_request:
        branches:
            - master
jobs:
    coverage:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v1
            # username ↓         repository ↓   your branch ↓
            - uses: sidharthv96/jest-coverage-report-action@test-branch
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
```

Don't forget that you need to run `npm run build`, before running action, because it uses compiled javascript.

After you have configurated your CI, create new PR in dummy repository, which will trigger action run. Hope my answer helps you!
