### ISSUE TITLE
proposal: Identify Coverage Added in PR

### ISSUE THREAD

**Issue by therynamo** [ArtiomTr/jest-coverage-report-action#134]
Hey there! 

We just started using this action - and so far it has been working really well for us. So thank you so much for taking the time to develop it for the community to use! I had a feature request in mind that I was wondering if we could iron out and get into the backlog (if you saw value in it). 

We think it would be really great to see some way of `%` difference of coverage added in any given PR. Since the diff is already being taken from the base branch, theoretically this would just be adding another value for the action to comment back with. But I'm not sure how to avoid overcrowding or produce the right information architecture. Either way - we'd really like some way to give props to those who take an active role in making the code base more tested. 

What are your thoughts on how this may provide value in your action?

**Comment by ArtiomTr** [comment]
Hello @therynamo,

Sorry, I do not fully understand your proposal - at the moment this action automatically adds information about increasing / decreasing test coverage. 

![image](https://user-images.githubusercontent.com/44021713/131251504-525fa9ae-cb61-4d93-9bca-438465493535.png)

Is this information enough for you? Or do you want to see more details? If so, could you please explain how it should look like?

**Comment by therynamo** [comment]
Hmmm - maybe I'm missing something - here is an example of code reduction - and I'm not seeing any indicators:

![Screen Shot 2021-09-01 at 1 20 22 PM](https://user-images.githubusercontent.com/8508556/131723597-a1f5735f-8021-4808-a2ea-8a0e079264f3.png)

**Comment by ArtiomTr** [comment]
@therynamo, could you please send your `action.yml` file? It looks like something went wrong :disappointed:

**Comment by therynamo** [comment]
```yaml

name: Jest Coverage
on:
    pull_request:
        branches:
            - <redacted>
            - <redacted>
jobs:
    coverage:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v1
            - uses: artiomtr/jest-coverage-report-action@v2.0-rc.4
              with:
                  github-token: ${{ secrets.<REDACTED> }}
                  package-manager: yarn
                  test-script: yarn jest --silent --ci --testLocationInResults --colors --coverage --json --outputFile=report.json --coverageReporters="text" --coverageReporters="text-summary" --forceExit


```
