### ISSUE TITLE
When calculating coverage in github action - it's failing on base branch coverage threshold

### ISSUE THREAD

**Issue by prabhasjoshi** [ArtiomTr/jest-coverage-report-action#152]
Hi,
I am using github action to calculate the coverage and push this info to my pr's.

here is my github coverage workflow. for
```
name: 'coverage'
on:
  pull_request:
    branches:
      - master

jobs:
  coverage:
    runs-on: [self-hosted]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Codebase
        uses: actions/checkout-action@v2
      - name: Use Node v14.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.1
      - name: Create code coverage
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: npm run test-coverage

```

I have specified by jest coverage to be 5 overall in my jest.config.js (apart from other things)

```
coverageThreshold: {
    global: {
      branches: 5,
      functions: 5,
      lines: 5,
      statements: 5,
    },
  },
```

I inspected the log of the actions workflow running.
when I use the any version above 2.0 like 2.0-rc.3 2.0-rc.4 or 2.0-rc.1 - it fails with this error 
```
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-23T07_20_12_604Z-debug.log
Head is ok, but base branch has not valid coverage. Some features will be disabled.
Error: testsFailed
Error: Process completed with exit code 1.
```

But If I use lower versions like 1.3 - then it works. What am I doing wrong

**Comment by ArtiomTr** [comment]
Hello @prabhasjoshi! 👋

For this action threshold needs to be specified via options, like this:

```yml
# ...

      - name: Create code coverage
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: npm run test-coverage
          #          ↓ value in percents
          threshold: 5
```

This action currently not resolves the value of the coverageThreshold parameter from jest.config.js 😢. The issue for this feature already exists -> #82
