### ISSUE TITLE
Is coverage-file still supported? 

### ISSUE THREAD

**Issue by PrestonII** [ArtiomTr/jest-coverage-report-action#161]
Does this still support the ability to use existing test reports as stated here: https://github.com/ArtiomTr/jest-coverage-report-action#use-existing-test-reports ?

I've been trying to use the `coverage-file` parameter but Github Actions is reporting it as not supported. Here's a copy of the `yaml` file:

````
name: "Test & Cover"

on: [pull_request, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install and Test 🔧
        run: |
          yarn
          yarn lint
          yarn test
        env:
          REACT_APP_DEV_ENV: dev
          REACT_APP_GOOGLE_MAP_KEY: ${{ __redacted__ }}
      - uses: actions/checkout@v2
      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.4
        with:
          github-token: ${{ __redacted__ }}
          skip-step: all
          package-manager: yarn
          coverage-file: "./coverage/coverage-final.json"
````
