### ISSUE TITLE
Unsupported platform for @next/swc-win32-x64-msvc@11.1.2

### ISSUE THREAD

**Issue by hsh2001** [ArtiomTr/jest-coverage-report-action#162]
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @next/swc-win32-x64-msvc@11.1.2: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    win32
npm ERR! notsup Valid Arch:  x64
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

**Comment by ArtiomTr** [comment]
Hello @hsh2001,

Looks like you're running your CI in linux environment, but `@next/swc-win32-x64-msvc` supports only windows platform. Try to change platform like this:

```yml
name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
# required platform ↓  
        runs-on: windows-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v1
            - uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  #   threshold: 80 # optional parameter
```
