### ISSUE TITLE
Node 16 - Error: ENOENT: no such file or directory, stat 'node_modules'

### ISSUE THREAD

**Issue by laurislokalise** [ArtiomTr/jest-coverage-report-action#166]
**Problem**
Action fails with the error
`Error: ENOENT: no such file or directory, stat 'app/node_modules'`
when running with Node 16.

It failed in two cases - please see the examples below. The only way it works is if npm install runs in `- name: NPM install` step and as part of `artiomtr/jest-coverage-report-action@v2.0-rc.4`.

With Node 14 everything worked out of the box and it was not necessary to have extra step that installs dependencies.

**Doesn't work**
Node modules are installed in `NPM install` step and `skip-step` is set to `install`.
```
name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.8.0

      - name: NPM install
        run: |
          cd app/
          npm install

      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./app/
          skip-step: install
```

**Doesn't work 2**
`- uses: artiomtr/jest-coverage-report-action@v2.0-rc.4` should handle installation of npm modules but it fails.
```
name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.8.0

      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./app/
```

**Works, but with issues**
Node modules are installed in `NPM install` step and installed again in `- uses: artiomtr/jest-coverage-report-action@v2.0-rc.4`. It works, but the installation happens twice which is not optimal.
```
name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.8.0

      - name: NPM install
        run: |
          cd app/
          npm install

      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./app/
  
```
