### ISSUE TITLE
No new coverage generated

### ISSUE THREAD

**Issue by AbdullahAli** [ArtiomTr/jest-coverage-report-action#171]
### Describe a bug

Hi team 👋🏼 

I have set up the action as describe and it is commenting the total coverage report.  However, it is not commenting the coverage of the new files even though the package does switch to the between the head and the base branch correctly and it does run the tests on both branches successfully

### Expected behavior

I would expect the comment to contain the coverage of the new files

### Details

-   Action version:
-   OS, where your action is running (windows, linux):
<details>
<summary>action.yml file</summary>

```yml
name: Pull Request Actions

on: pull_request

jobs:
  coverage:
    name: Check Test Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.22.0

      - name: Install dependencies
        working-directory: .
        run: yarn install --immutable

      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: .
          package-manager: yarn
          test-script: yarn jest --silent --ci --coverage --testLocationInResults --json --outputFile=report.json
```
</details>

<details>
<summary>Screenshots</summary>

<img width="838" alt="Screenshot 2021-10-01 at 14 11 50" src="https://user-images.githubusercontent.com/1620134/135626027-81a2e27e-65d2-4954-bdec-1df7fc94e173.png">
