### ISSUE TITLE
Some errors are not reported in `v2.0-rc.5`

### ISSUE THREAD

**Issue by herberttn** [ArtiomTr/jest-coverage-report-action#178]
### Describe a bug

I've been testing `v2.0-rc.5` and the action is failing (which is ok, part of life). But the real problem is that it does not tell me what happened. It does not post the comment on the pull request and it does not output anything to the action execution log (not even with debug logging enabled).

### Expected behavior

When something goes wrong, it would be useful to know what. Messages and especially errors should always be sent to the action log, so it's possible to troubleshoot problems.

### Details

- Action version: `v2.0-rc.5`
- OS, where your action is running (windows, linux): `ubuntu-latest`
- <details><summary>action.yml file</summary>

  ```yml
  env:
    node: 16.8
  
  jobs:
    build-and-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            cache: npm
            node-version: ${{ env.node }}
        - run: npm ci
        - run: npx tsc
        - run: npx jest --ci --coverage --json --testLocationInResults
        - uses: actions/upload-artifact@v2
          if: success() || failure()
          with:
            name: coverage-reports-${{ github.base_ref }}
            path: test/coverage/*.json
        - uses: actions/download-artifact@v2
          if: success() || failure()
          with:
            name: coverage-reports-${{ github.base_ref }}
            path: test/coverage/base
        - uses: artiomtr/jest-coverage-report-action@v2.0-rc.5
          if: success() || failure()
          with:
            annotations: failed-tests
            base-coverage-file: ./test/coverage/base/coverage-final.json
            coverage-file: ./test/coverage/coverage-final.json
            github-token: ${{ github.token }}
  ```
  </details>

- <details><summary>Screenshots</summary>
        
    ![image](https://user-images.githubusercontent.com/5903869/136841154-4064c125-41fb-4df5-936b-1d05f555cf72.png)

  </details>

### Additional context

I'm providing both the `coverage-file` and the `base-coverage-file`, and the only thing that the log reports is switching branches, and then it unexpectedly fails. By looking at the source, I imagine something goes wrong between switching to the base branch and posting the comment to the pull request, which prevents the comment to be posted and therefore the error is not shown anywhere.

I'm opened #179 to make `DataCollector` output messages and errors to the log as it's receiving them? That way no error would be lost by accident and all messages and errors should be correctly interleaved with the `stdout` of child processes (for easier troubleshooting).

PS: GitHub doesn't allow me to add the `next` label as the template asks.
