### ISSUE TITLE
Not able to set a working-directory

### ISSUE THREAD

**Issue by hetunandu** [ArtiomTr/jest-coverage-report-action#18]
I was trying this action out but it keeps failing to find the package.json file in `/github/workspace` directory
<img width="1256" alt="Screenshot 2021-03-20 at 6 46 48 PM" src="https://user-images.githubusercontent.com/12022471/111870816-d8d2b580-89ac-11eb-8f33-fe4c92975c1c.png">
 
my test-script is 
```
"test:unit": npx jest -b --colors --no-cache --silent --coverage --coverageReporters='text' --coverageReporters='text-summary'
```

**Comment by ArtiomTr** [comment]
Hello! Github Actions has the ability to specify the working directory ([link](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun)). 

For example:
```diff
name: 'coverage'
on:
    pull_request:
        branches:
            - master
jobs:
    coverage:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v1
            - uses: artiomtr/jest-coverage-report-action@v1.0
+             working-directory: <dir>
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
```

Could you confirm please, if that solution is suit you? Or `jest-coverage-report-action` should have something like `cwd` option?

**Comment by hetunandu** [comment]
Oops. I was passing this argument at the wrong level. This works. Thanks 😄

**Comment by Marsup** [comment]
GitHub seems to refuse `working-directory` when used with `uses`, how did you make it work?

**Comment by ArtiomTr** [comment]
> GitHub seems to refuse `working-directory` when used with `uses`, how did you make it work?

Could you please send your configuration that is not working? I will try to reproduce the problem.

**Comment by Marsup** [comment]
Identical to the one you posted above. I get this error `The workflow is not valid. .github/workflows/ci_test.yml (Line: 74, Col: 7): Unexpected value 'working-directory'`

**Comment by hamish-milne** [comment]
Yep; `working-directory` is only supported for `run` steps. @ArtiomTr it would be super useful to have this as a feature

**Comment by ArtiomTr** [comment]
Could you please confirm if this solution helped you?

You can try it with this configuration:

```yml
name: 'coverage'
on:
    pull_request:
        branches:
            - master
jobs:
    coverage:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v1
            - uses: artiomtr/jest-coverage-report-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  working_directory: <directory>
```

Please note that a new version has not been released at the moment, so the version from the master branch is used: `artiomtr/jest-coverage-report-action@master`
