### ISSUE TITLE
Using test-script input with a package manager and double hyphen causes unexpected results

### ISSUE THREAD

**Issue by thomasplevy** [ArtiomTr/jest-coverage-report-action#185]
### Describe a bug

My project has an existing test run script (using npm): `npm run test:pkgs`

After reviewing the action docs I decided that using the `test-script` input to use my script would work, but I'd have to add additional parameters (per the warning in the docs). My `test-script` input became: `npm run test:pkgs -- --coverage --coverageReporters="text" --coverageReporters="text-summary"`

When running the workflow I'm encountering unexpected results because my script already contains a double hyphen and the action *adds* one automatically, resulting in the actual script being run:

`/opt/hostedtoolcache/node/14.18.1/x64/bin/npm run test:pkgs -- --coverage --coverageReporters=text --coverageReporters=text-summary -- --ci --json --coverage --testLocationInResults --outputFile=report.json`

Note the two sets of double hyphens

### Expected behavior

I'd expect only a single set of hyphens to be included

### Details

-   Action version: 2.0-rc.6
-   OS, where your action is running (windows, linux): ubuntu-latest
-   <details><summary>action.yml file</summary>

        ```yml
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node_modules
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install NPM Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run test suite
        # uses: artiomtr/jest-coverage-report-action@v2.0-rc.6
        uses: gocodebox/jest-coverage-report-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: install
          threshold: 50
          test-script: npm run test:pkgs -- --coverageReporters="text" --coverageReporters="text-summary"
        ```

    </details>

### Additional context

I realize that I can very simply fix this by modifying my script in my package.json file.

However, I've already made a few small changes to this on a fork and tested it to work. Based on some existing (and new) tests I've added it shouldn't have any detrimental affect. The changes I made add a double hyphen only when a double hyphen doesn't already exist in the custom script. I'm going to open a PR in a moment in case you might accept this change.

Thanks!
