### ISSUE TITLE
Action comments successful results on PR, but still fails

### ISSUE THREAD

**Issue by gtsop-pf** [ArtiomTr/jest-coverage-report-action#188]
### Describe a bug

The action runs correctly:
- tests run
- tests pass
- results comment appear on PR

The action is marked as failed

### Expected behavior

The action should be marked as successful 

### Details

-   Action version: v2.0-rc.6
-   OS, where your action is running (windows, linux): ubuntu-latest
-   <details><summary>action.yml file</summary>

        ```yml
        name: Tests
        
        on: [push]
        
        jobs:
        
          test-unit:
            runs-on: ubuntu-latest
            steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '14'
            - name: Install modules
              run: npm install
            - name: Tests:unit
              run: npm run ci:test:unit
            - uses: artiomtr/jest-coverage-report-action@v2.0-rc.6
              with:
                github-token: ${{ secrets.GITHUB_TOKEN  }}
                test-script: npm run ci:test:coverage
        ```

    </details>

- <details>
    <summary>Screenshots</summary>
    
    ![action-error-log](https://user-images.githubusercontent.com/90187915/139683094-1ef6733c-79cd-48fc-a3d3-6c65a912fcde.png)
    ![pr-check-fails](https://user-images.githubusercontent.com/90187915/139683097-aa466f91-0e52-4bc1-869e-2839479304dd.png)
    ![pr-comment-success](https://user-images.githubusercontent.com/90187915/139683099-2be94609-d7c5-4db0-9802-6f2387e01722.png)
    
    </details>
    
 -   <details>
     <summary>package.json script</summary>
     
      ```json
      {
          "ci:test:coverage": "craco test --ci --json --coverage --testLocationInResults --outputFile=\"report.json\"",
      }
      ```
  </details>
