### ISSUE TITLE
Generic error formed after running action

### ISSUE THREAD

**Issue by EvanSays** [ArtiomTr/jest-coverage-report-action#189]
### Describe a bug

- Tests run
- Tests pass
- Action fails

### Expected behavior

- Action is successful

### Details

-   Action version: v2.0-rc.5
-   OS, where your action is running (windows, linux): unbuntu-latest
-   <details><summary>action.yml file</summary>

    ```yml
    name: Test
    on:
      push:
        branches: 
          - '**'
          - '!master'

    jobs:
      test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2.1.2
            with:
              node-version: 17.0.0
          - run: yarn --frozen-lockfile
          - run: cp src/utils/envs/templates/* src/utils/envs
          - uses: artiomtr/jest-coverage-report-action@v2.0-rc.5
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              package-manager: yarn
              annotations: none
              test-script: npx jest --silent --ci --coverage --coverageReporters="text" --coverageReporters="text-summary"
    ```

    </details>

-   <details><summary>Screenshots</summary>

     ![Screen Shot 2021-11-04 at 11 06 20 AM](https://user-images.githubusercontent.com/19983952/140339311-673e8a60-fb32-4ca8-b14c-22190e2cde2b.png)

    </details>

**Comment by EvanSays** [comment]
![image (2)](https://user-images.githubusercontent.com/19983952/140406290-d9778b9a-b3c0-4d25-a3e6-5b1937a8be2a.png)
In this example above, would the action fail because the test percentage is below the minimum? Is that normal behavior?

**Comment by ArtiomTr** [comment]
Hello @EvanSays 👋,

Yes, this is the intended behavior if the `threshold` property is specified. But, in your `action.yml` file, there is no `threshold` option, so this means action should only report coverage and not fail.

Could you please try to run `v2.0-rc.6` version, and then make a screenshot of **full** console. In rc.6 version action reports much more information, so I could more easily spot the error 😄

**Comment by EvanSays** [comment]
@ArtiomTr
![Screen Shot 2021-11-05 at 11 23 58 AM](https://user-images.githubusercontent.com/19983952/140535364-a6c0f7ac-2f02-4ee9-8377-9fad54253964.png)
![Screen Shot 2021-11-05 at 11 24 13 AM](https://user-images.githubusercontent.com/19983952/140535371-b1b8b6ea-49d9-4943-8ae4-b379fe55d181.png)

**Comment by ArtiomTr** [comment]
Hm, very strange issue. Looks like all tests pass, but command `npx jest ...` terminates with non-zero exit code (1). I see only one possible problem with your `action.yml` file, is that you're using `yarn` package manager and `npx` as test runner. Try to use this configuration:
```yml
name: Test
on:
  push:
    branches: 
      - '**'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 17.0.0
      - run: yarn --frozen-lockfile
      - run: cp src/utils/envs/templates/* src/utils/envs
      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
          annotations: none
          test-script: yarn jest
```
