### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by mathiasmoeller** [ArtiomTr/jest-coverage-report-action#196]
### Describe a bug

When running the action while skipping all steps, generating the coverage report fails with
```
Error: TypeError: Cannot convert undefined or null to object
```

### Expected behavior

The report should be generated.

### Details

-   Action version: `artiomtr/jest-coverage-report-action@v2.0-rc.6`
-   OS, where your action is running (windows, linux): `ubuntu-latest`
-   <details><summary>action.yml file</summary>

        ```
        - run: yarn install --frozen-lockfile --non-interactiv
        - run: yarn --silent jest --silent --ci --collect-coverage
          name: Jest tests
        - uses: artiomtr/jest-coverage-report-action@v2.0-rc.6
          name: Coverage Report
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            coverage-file: ./coverage/coverage-final.json
            skip-step: all
            annotations: none
        ```

    </details>

-   <details><summary>Screenshots</summary>

    ![image](https://user-images.githubusercontent.com/8833906/141951945-5730ebbc-e9fa-4351-a105-c041dad41baf.png)

    </details>

### Additional context

As you can see on the screenshot, the Jest tests run successful and the coverage report is generated. The filename of the coverage report seems to be correct. In a previous iteration I forgot to generate the coverage report and the action failed while trying to load it. So I think that's not the issue.

Thanks already for the help!

**Comment by mathiasmoeller** [comment]
Okay this was my bad (as usual). I didn't read the part about custom coverage commands carefully enough. 
The command you specified (`npx jest --silent --ci --coverage --coverageReporters="text" --coverageReporters="text-summary"`) does not generate a coverage report file though. If I now want to generate a report on my master branch and compare it, which command should I use to generate it? Since the result of `yarn --silent jest --silent --ci --collect-coverage` was not readable by the github action?

Thanks a lot!

**Comment by mathiasmoeller** [comment]
Okay this was my bad (as usual). I didn't read the part about custom coverage commands carefully enough.
I do, however, still have issues with the comparison with the basebranch. It is skipped every time:
```
Switching to base branch skipped
```
It is running in a pull request so [this](https://github.com/ArtiomTr/jest-coverage-report-action/blob/master/src/run.ts#L55-L61) should always evaluate to false and not skip it right?

**Comment by ArtiomTr** [comment]
Hello @mathiasmoeller,

Yes, if code works correctly, it should evaluate to false and not skip switching to branch. If it skips your action anyway, there are 2 possible reasons:
1. Your action is running not for PR. To ensure that action will run always only in pull request, please add these lines:
```yml
on:
    pull_request:
        branches:
        # your main branch name
            - main
```
And `on` section should contain only one single event. Otherwise this could lead to the effect that action is triggered by another event.
2. Possibly, GitHub Action API has changed, and the scheme of payload changed.
Could you check the 1st point? If it doesn't work, I will try to repeat this problem myself and solve it.
