### ISSUE TITLE
Installing dependencies failed

### ISSUE THREAD

**Issue by sudo-kaizen** [ArtiomTr/jest-coverage-report-action#203]
### Describe a bug

Acton fails to install dependencies, and ends up no running tests
Repository is private

### Expected behavior

That it installs dependencies, runs tests and comments with its report

### Details

-   Action version: v2.0-rc.6
-   OS, where your action is running (windows, linux): linux
-   <details><summary>action.yml file</summary>
```yml
          name: 'coverage'
          on:
          pull_request:
            branches:
                 - master
                 - develop
          jobs:
              coverage:
                  runs-on: ubuntu-latest
                  if: "!contains(github.event.head_commit.message, '[skip ci]')"
                  steps:
                      - uses: actions/checkout@v1
                      - uses: Artiomtr/jest-coverage-report-action@v2.0-rc.6
                        with:
                            github-token: ${{ secrets.GITHUB_TOKEN }}
                            package-manager: yarn
                            #   threshold: 80 # optional parameter
```
</details>

-   <details><summary>Screenshots</summary>
```bash
Running using node v16.13.0
Begin initialization stage...
Initialization stage ended
Begin head coverage collection...
Begin installing dependencies...
(node:1488) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Installing dependencies failed
Error: Error: ENOENT: no such file or directory, stat 'node_modules'
Installing dependencies ended
Begin running tests...
/usr/local/bin/npx jest --ci --json --coverage --testLocationInResults --outputFile=report.json
npm WARN exec The following package was not found and will be installed: jest
● Validation Error:

  Module ts-jest in the transform option was not found.
         <rootDir> is: /home/runner/work/*******i/*****/src

  Configuration Documentation:
  https://jestjs.io/docs/configuration

Running tests failed
Error: Error: The process '/usr/local/bin/npx' failed with exit code 1
Running tests ended
Begin collecting coverage...
Collecting coverage failed
Error: Coverage output file not found. (file "report.json" not found)
Collecting coverage ended
Begin parsing coverage...
Parsing coverage skipped
Parsing coverage ended
Head coverage collection failed
Error: Getting code coverage data failed.
Head coverage collection ended
Begin switching to base branch...
/usr/bin/git fetch --all --depth=1
Fetching origin
fatal: could not read Username for 'https://github.com': No such device or address
error: Could not fetch origin
Error fetching git repository Error: The process '/usr/bin/git' failed with exit code 1
    at Xn._setResult (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0-rc.6/dist/index.js:9:17173)
    at Xn.CheckComplete (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0-rc.6/dist/index.js:9:16763)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0-rc.6/dist/index.js:9:15756)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
/usr/bin/git checkout -f develop
Previous HEAD position was ed914cb Merge af10e8a82ac9201ec903bc471e88ae783cb1eabb into d00e0afb3f69c76acea5d23753483a8286338d36
Switched to a new branch 'develop'
Branch 'develop' set up to track remote branch 'develop' from 'origin'.
Switching to base branch ended
Begin base coverage collection...
Begin installing dependencies...
Installing dependencies failed
Error: Error: ENOENT: no such file or directory, stat 'node_modules'
Installing dependencies ended
Begin running tests...
/usr/local/bin/npx jest --ci --json --coverage --testLocationInResults --outputFile=report.json
● Validation Error:

  Module ts-jest in the transform option was not found.
         <rootDir> is: /home/runner/work/****/***/src

  Configuration Documentation:
  https://jestjs.io/docs/configuration

Running tests failed
Error: Error: The process '/usr/local/bin/npx' failed with exit code 1
Running tests ended
Begin collecting coverage...
Collecting coverage failed
Error: Coverage output file not found. (file "report.json" not found)
Collecting coverage ended
Begin parsing coverage...
Parsing coverage skipped
Parsing coverage ended
Base coverage collection failed
Error: Getting code coverage data failed.
Base coverage collection ended
Begin generating report...
Generating report failed
Error: TypeError: Cannot read properties of undefined (reading 'success')
Generating report ended
Begin report publish...
Report publish skipped
Report publish ended
Begin failed tests' annotations publication...
Failed tests' annotations publication skipped
Failed tests' annotations publication ended
Begin coverage annotations publication...
Coverage annotations publication skipped
Coverage annotations publication ended
Error: Jest coverage report action failed
Error: Process completed with exit code 1.
0s
```
    </details>

**Comment by patrickacioli** [comment]
Same here. 

My config:

```
  coverage:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: none
```

**Comment by sudo-kaizen** [comment]
@patrickacioli I tried using v1 too and I got errors too

I'm wondering if this is a problem with Github and not the action.

**Comment by rafauke** [comment]
@sudo-kaizen have you checked if you have any private repositiories in your `package.json`? This resulted in failed `yarn` command on my side, which then affected the rest of the steps.

**Comment by sudo-kaizen** [comment]
Thanks @rafauke I've checked and I don't have any private packages in my package.json file

**Comment by patrickacioli** [comment]
Guys, try the following action. We add Node version 14.x.


```
name: Jest Coverage
on: ["push"]

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: User Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```
