### ISSUE TITLE
Code coevrage for individual files doesn’t show up in the comment if tests files are modified but corresponding source file isn't changed

### ISSUE THREAD

**Issue by shubhnik** [ArtiomTr/jest-coverage-report-action#207]
### Describe a bug

If I write unit tests and increase code coverage for a file that already exists, it doesn't show the improved coverage for that specific file in the comment.

### Expected behavior
When test files are improved without touching anything in source files, the code coverage increment should show up in the comments.

### Details

-   Action version: `artiomtr/jest-coverage-report-action@v2.0-rc.6`
-   OS, where your action is running (windows, linux): `linux`
-   <details><summary>action.yml file</summary>

        ```yml
        jobs:
          coverage:
              runs-on: self-hosted
              if: "!contains(github.event.head_commit.message, '[skip ci]')"
              steps:
                - name: Checkout Codebase
                  uses: actions/checkout@v2
                  with:
                    token: ${{ secrets.CI_BOT_TOKEN }}
                - name: Setup Node v14
                  uses: actions/setup-node@v2
                  with:
                    node-version: "14"
                - name: Install Yarn
                  run: npm install -g yarn
                - name: Code coverage
                  uses: artiomtr/jest-coverage-report-action@v2.0-rc.6
                  with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    test-script: yarn test:coverage
                    package-manager: yarn
                    annotations: none
        ```

    </details>

-   <details><summary>Screenshots</summary>

    1. Changes in 2 test files which improves code coverage:
           <img width="1346" alt="Screenshot 2021-12-20 at 1 33 11 PM" src="https://user-images.githubusercontent.com/9150371/146733110-0461b5e5-041b-4b4b-aaae-3dd79c5c92ab.png">
           
    2. But those improved changes for the respective files is not shown individually in the comment:
           <img width="781" alt="Screenshot 2021-12-20 at 1 33 29 PM" src="https://user-images.githubusercontent.com/9150371/146733228-6328abb6-4dd7-4bfe-8b50-3e4a60d949cc.png">
</details>
