### ISSUE TITLE
Error: HttpError: You must authenticate via a GitHub App.

### ISSUE THREAD

**Issue by graemelambert** [ArtiomTr/jest-coverage-report-action#209]
Getting `Error: HttpError: You must authenticate via a GitHub App.` in the output.

```
Test Suites: 16 passed, 16 total
Tests:       94 passed, 94 total
Snapshots:   15 passed, 15 total
Time:        8.251 s, estimated 17 s
Ran all test suites.
Test results written to: report.json
Running tests ended
Begin collecting coverage...
Collecting coverage ended
Begin parsing coverage...
Parsing coverage ended
Base coverage collection ended
Begin generating report...
Generating report ended
Begin report publish...
Report publish ended
Begin failed tests' annotations publication...
Failed tests' annotations publication skipped
Failed tests' annotations publication ended
Begin coverage annotations publication...
Coverage annotations publication failed
Error: HttpError: You must authenticate via a GitHub App.
Coverage annotations publication ended
Error: Jest coverage report action failed
Error: Process completed with exit code 1.
```

Not sure exactly where I've gone wrong here?  The workflow is set up with this;
```
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          threshold: 100
```

`GH_TOKEN` is a personal access token with permission to access repositories.

**Comment by vishnu-wednesday** [comment]
You can try with annotations turned off for now. I believe there is already an open issue for this. 
https://github.com/ArtiomTr/jest-coverage-report-action#change-annotaions

**Comment by bfine9618** [comment]
Having the same issue

**Comment by ArtiomTr** [comment]
Hello @graemelambert :wave:,

Sorry for the late reply. It's not an issue with action. Your token does not have permission to publish annotations. You can disable them or change the token. It is recommended to pass `${{ github.token }}` because it already has enough permissions to do the stuff. (remember that `${{ github.token }}` has many privileges, and it is not safe to use it everywhere, so consider the risks before using it.)

Hope this solution helps you! I'm closing the issue for now, but if anyone encounters the same issue, feel free to add comments and ping me.

**Comment by graemelambert** [comment]
@ArtiomTr ok, I've removed the token line and all I've got now is this;

```
    steps:
      - uses: actions/checkout@v2
      - uses: artiomtr/jest-coverage-report-action@v2.0.1
        with:
          threshold: 100
```

and now I get a different error;

```
Switching back to original branch ended
Begin stages.checkthreshold...
stages.checkThreshold ended
Begin generating report...
Generating report ended
Begin report publish...
Report publish ended
Begin failed tests' annotations publication...
Failed tests' annotations publication skipped
Failed tests' annotations publication ended
Begin coverage annotations publication...
Coverage annotations publication failed
Error: HttpError: Invalid request.

"end_line", "start_line" weren't supplied.
"end_line", "start_line" weren't supplied.
"end_line", "start_line" weren't supplied.
Coverage annotations publication ended
Error: Jest coverage report action failed
Error: Process completed with exit code 1.
```

Shall I raise a new issue?
