### ISSUE TITLE
base-coverage-file does not seem to be working

### ISSUE THREAD

**Issue by chrisui** [ArtiomTr/jest-coverage-report-action#214]
### Describe a bug

Despite providing a file that exists it does not appear to be used.

### Expected behavior

I see a diff with the base report.

### Details

-   Action version: rc-6
-   OS, where your action is running (windows, linux): linux
-   <details><summary>action.yml file</summary>

```yml
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 1
          skip-step: all
          annotations: failed-tests
          coverage-file: ./coverage/report.json
          base-coverage-file: ./coverage/base.json
 ```

### Additional context

```
Running using node v14.18.2
Begin initialization stage...
Initialization stage ended
Begin head coverage collection...
Begin installing dependencies...
Installing dependencies skipped
Installing dependencies ended
Begin running tests...
Running tests skipped
Running tests ended
Begin collecting coverage...
Loading code coverage from file: ./coverage/report.json
Collecting coverage ended
Begin parsing coverage...
Parsing coverage ended
Head coverage collection ended
Begin switching to base branch...
Switching to base branch skipped
Switching to base branch ended
Begin base coverage collection...
Base coverage collection skipped
Base coverage collection ended
Begin generating report...
Generating report ended
Begin report publish...
Report publish ended
Begin failed tests' annotations publication...
Failed tests' annotations publication skipped
Failed tests' annotations publication ended
Begin coverage annotations publication...
Coverage annotations publication skipped
Coverage annotations publication ended
```
