### ISSUE TITLE
Action failing after upgrading from Jest 26 to 27

### ISSUE THREAD

**Issue by davecowart** [ArtiomTr/jest-coverage-report-action#216]
### Describe a bug

_This is for `v2.0-rc.6`, but I'm not able to add labels to the issue._

After upgrading my project to use Jest 27 (from 26), `jest-coverage-report-action` is running all the tests successfully but failing to mark the step as successful. The step seems to time out after close to 30 minutes (while a successful run takes about 6 minutes), and this error is included in the output: `Error: The process '/opt/hostedtoolcache/node/14.18.2/x64/bin/npx' failed with exit code null`.

### Details

-   Action version: `v2.0-rc.6`
-   OS, where your action is running (windows, linux): `linux`
-   <details><summary>action.yml file</summary>
    ```yml

        name: 'Test Coverage'
        
        on:
          pull_request:
          pull_request_target:
        
        jobs:
          code-coverage:
            runs-on: ubuntu-latest
            # If the PR is coming from a fork (pull_request_target), ensure it's opened by "dependabot[bot]".
            # Otherwise, clone it normally.
            if: |
              (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
              (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
            steps:
              - uses: actions/checkout@v2
              - uses: actions/setup-node@v2
                with:
                  node-version: '14'
        
              - name: Get yarn cache directory path
                id: yarn-cache-dir-path
                run: echo "::set-output name=dir::$(yarn cache dir)"
        
              - uses: actions/cache@v2
                id: yarn-cache
                with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                    ${{ runner.os }}-yarn-
        
              - uses: artiomtr/jest-coverage-report-action@v2.0-rc.6
                with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  threshold: 50
                  package-manager: yarn
                  annotations: failed-tests
            ```

    </details>

-   <details><summary>Screenshots</summary>

    ![image](https://user-images.githubusercontent.com/154992/147994319-79c10f79-04e0-4e44-bde1-db1b83832143.png)

    ![image](https://user-images.githubusercontent.com/154992/147994585-30368f2f-3d9d-4405-bdce-e8b41f4f6958.png)

    </details>

### Additional context

Final output from the failing step:

```
Test Suites: 266 passed, 266 total
Tests:       804 passed, 804 total
Snapshots:   0 total
Time:        147.017 s
Ran all test suites.
Test results written to: report.json
Running tests ended
Begin collecting coverage...
Collecting coverage ended
Begin parsing coverage...
Parsing coverage ended
Base coverage collection ended
Begin generating report...
Generating report ended
Begin report publish...
Report publish ended
Begin failed tests' annotations publication...
Failed tests' annotations publication skipped
Failed tests' annotations publication ended
Begin coverage annotations publication...
Coverage annotations publication skipped
Coverage annotations publication ended
Error: Jest coverage report action failed
Error: Process completed with exit code 1.
```
