### ISSUE TITLE
Coverage threshold doesn't seem to work

### ISSUE THREAD

**Issue by mentos1386** [ArtiomTr/jest-coverage-report-action#223]
### Describe a bug

When using Jest with the following config, the action fails with an error.
```json
"coverageThreshold": {
  "global": {
    "lines": 80
  }
},
```

### Expected behavior

To not see the error.

### Details

-   Action version: `v2`
-   OS, where your action is running (windows, linux): `linux`
-   `action.yml`
```yml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - name: Authenticate NPM
        run: eval "echo \"$(cat .npmrc.tpl)\"" > .npmrc

      - uses: ArtiomTr/jest-coverage-report-action@v2
```

![image](https://user-images.githubusercontent.com/1910649/151574309-62e018a0-81f2-402e-85d2-55dc2d877508.png)

### Additional context

```
Begin running tests...
/usr/local/bin/npx jest --ci --json --coverage --testLocationInResults --outputFile=report.json
PASS src/<redacted>.ts (14.579 s)
<redacted>
PASS src/<redacted>.ts
Jest: "global" coverage threshold for lines (80%) not met: 31.15%

Test Suites: 7 passed, 7 total
Tests:       29 passed, 29 total
Snapshots:   0 total
Time:        25.117 s, estimated 29 s
Ran all test suites.
Test results written to: report.json
Running tests failed
Error: Error: The process '/usr/local/bin/npx' failed with exit code 1
```

---

Is jest not supposed to exit with error code 1?
