### ISSUE TITLE
Passing coverage but action not completing

### ISSUE THREAD

**Issue by adamrturman** [ArtiomTr/jest-coverage-report-action#23]
I'm very excited to incorporate this tool into my workflow! 

I've customized the testing script:

```
name: Testing and Linting

on:
  pull_request:

jobs:
  coverage:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v1
            - uses: artiomtr/jest-coverage-report-action@v1.2
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  test_script: npm run test -- --coverage --coverageReporters="text" --coverageReporters="text-summary" --watchAll
                  threshold: 90
  test:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Linter
        run: npm run lint
```
                  
and I see the coverage report in the logs passing the threshold                  

![Github Actions Log](https://user-images.githubusercontent.com/67024033/116472065-037d1d00-a83b-11eb-86ab-a63973fc9319.png)

but the `coverage` action continues to run until I manually stop it. What I can I try to fully implement this tool?
