### ISSUE TITLE
Flag skip-step and coverage-file are not work as excepted

### ISSUE THREAD

**Issue by huikaihoo** [ArtiomTr/jest-coverage-report-action#230]
### Describe a bug

When setup `skip-step` to `all` and  `coverage-file`, and run the pipeline, it will checkout main branch and try to install and run jest.
Why switch branch is need? As the test should run on the branch that need to merge and check the test result. No description or explanation about this behavior.
And `skip-step` and  `coverage-file` are not behave as excepted.

### Expected behavior

No git related actions and No installation and running jest action should be performed as skip-step is set and coverage-file is provided.

### Details

-   Action version: `ArtiomTr/jest-coverage-report-action@v2.0.3`
-   OS, where your action is running (windows, linux): `ubuntu-latest`
-   <summary>action.yml file</summary>
```yml
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
       ....
      - name: Show report
        uses: ArtiomTr/jest-coverage-report-action@v2.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: all
          package-manager: yarn
          annotations: failed-tests
          coverage-file: report.json
          threshold: 80
```

-   <details><summary>Screenshots</summary>

        Run ArtiomTr/jest-coverage-report-action@v2.0.3
          with:
            github-token: ***
            skip-step: all
            package-manager: yarn
            annotations: failed-tests
            coverage-file: report.json
            threshold: 80
            test-script: npx jest
            icons: emoji
          env:
            TARGET: common
            NVMRC: v16.6.2
        Run $GITHUB_ACTION_PATH/run.sh
          $GITHUB_ACTION_PATH/run.sh
          shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
          env:
            TARGET: common
            NVMRC: v16.6.2
            INPUT_GITHUB-TOKEN: ***
            INPUT_TEST-SCRIPT: npx jest
            INPUT_THRESHOLD: 80
            INPUT_WORKING-DIRECTORY:
            INPUT_ICONS: emoji
            INPUT_ANNOTATIONS: failed-tests
            INPUT_PACKAGE-MANAGER: yarn
            INPUT_SKIP-STEP: all
            INPUT_CUSTOM-TITLE:
            INPUT_COVERAGE-FILE: report.json
            INPUT_BASE-COVERAGE-FILE:
        Running using node v16.6.2
        Begin initialization stage...
        Initialization stage ended
        Begin stages.parsethreshold...
        stages.parseThreshold ended
        Begin head coverage collection...
        Begin installing dependencies...
        Installing dependencies skipped
        Installing dependencies ended
        Begin running tests...
        Running tests skipped
        Running tests ended
        Begin collecting coverage...
        Loading code coverage from file: report.json
        Collecting coverage ended
        Begin parsing coverage...
        Parsing coverage ended
        Head coverage collection ended
        Begin switching to base branch...
        /usr/bin/git fetch --all --depth=1
        Fetching origin
        /usr/bin/git checkout -f main
        Already on 'main'
        Your branch is up to date with 'origin/main'.
        Switching to base branch ended
        Begin base coverage collection...
        Begin installing dependencies...
        /usr/local/bin/yarn install
        ➤ YN0000: ┌ Resolution step
        Resolution step
        ➤ YN0000: └ Completed in 0s 879ms

        ➤ YN0000: ┌ Post-resolution validation
        Post-resolution validation
        ➤ YN0000: └ Completed
        Installing dependencies ended
        Begin running tests...
        /opt/hostedtoolcache/node/16.6.2/x64/bin/npx jest --ci --json --coverage --testLocationInResults --outputFile=report.json

    </details>

**Comment by ArtiomTr** [comment]
Hello @huikaihoo 👋,

The action is working as expected. The `skip-step` option works only for current branch. However, to do the comparisons, and report increased / new files coverage information, action also needs to collect base branch coverage. This is the reason, why action is checking out to the base branch - it needs to collect coverage, as you've not provided any information about it.

What you can do to prevent action from collecting that coverage, you can specify the `base-coverage-file` option:

```yml
uses: ArtiomTr/jest-coverage-report-action@v2.0.3
with:
    base-coverage-file: base-report.json
```
You can collect base-branch coverage information manually to the `base-report.json` file. Or you can specify same path for both `base-coverage-file` and `coverage-file` options. But, you will opt-out of all coverage comparison features.
