### ISSUE TITLE
Status of coverage icon indicators dont match thresholds set in jest.config.js

### ISSUE THREAD

**Issue by stuartin** [ArtiomTr/jest-coverage-report-action#235]
### Describe a bug

Firstly thanks for taking the time to create this GitHub action! It's very nice and working pretty much exactly how we want it to.

We are however experiencing some confusion around the 'Status of coverage' traffic light icons in the first column of the report.
As per below, both **Branches** and **Functions** are reporting that they are 'Under the threshold', however our `jest.config.js` has the thresholds set as per below so they should be 'Slightly more then threshold'
![image](https://user-images.githubusercontent.com/13344713/155630255-90676bfa-5d79-46b2-82f9-341d75ea2033.png)

```js
  coverageThreshold: {
    global: {
      branches: 56,
      functions: 47,
      lines: 78,
      statements: 79,
    },
  }
```

### Expected behavior

The 'Status of coverage' column icons should show the correct color based on what is set in the `jest.config.js` file.

### Details

-   Action version: `v2`
-   OS, where your action is running (windows, linux): `linux`
-   <details><summary>action.yml file</summary>

      ```yml
        - uses: ArtiomTr/jest-coverage-report-action@v2
          with:
            test-script: yarn jest
            package-manager: yarn
            skip-step: install
            annotations: none
      ```

    </details>

-   <details><summary>Screenshots</summary>

      ![image](https://user-images.githubusercontent.com/13344713/155630255-90676bfa-5d79-46b2-82f9-341d75ea2033.png)

    </details>

### Additional context

N/A
