### ISSUE TITLE
Skip switching branches

### ISSUE THREAD

**Issue by Raigen** [ArtiomTr/jest-coverage-report-action#236]
### Idea

I want to skip switching branches to the base branch and back entirely when all reports are supplied initially.

### Description

We are working with a fork workflow and all PRs are from forked repositories. That means switching back to the PR branch fails because that branch does not exists on the origin repository.
We generate the base coverage report on the main branch and save it with actions/cache for further usage in PRs. This way we can provide the base coverage report without the need to run the tests twice each PR. It works good, the base report is used and running the tests is skipped. But still the branch is beeing switched to master and back afterwards, which fails.
```
Switched to a new branch 'master'
branch 'master' set up to track 'origin/master'.
Switching to base branch ended
Begin base coverage collection...
Begin installing dependencies...
Installing dependencies skipped
Installing dependencies ended
Begin running tests...
Running tests skipped
Running tests ended
Begin collecting coverage...
Loading code coverage from file: coverage/base-report.json
Collecting coverage ended
Begin parsing coverage...
Parsing coverage ended
Base coverage collection ended
Begin switching back to original branch...
/usr/bin/git fetch --all --depth=1
Fetching origin
/usr/bin/git checkout -f chore/EPNG-8726-compare-coverage-with-base
error: pathspec 'chore/EPNG-8726-compare-coverage-with-base' did not match any file(s) known to git
Switching back to original branch failed
Error: Error: The process '/usr/bin/git' failed with exit code 1
Error: The process '/usr/bin/git' failed with exit code 1
    at jp._setResult (/home/runner/work/_actions/artiomtr/jest-coverage-report-action/v2/dist/index.js:10:17263)
    at jp.CheckComplete (/home/runner/work/_actions/artiomtr/jest-coverage-report-action/v2/dist/index.js:10:16853)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/artiomtr/jest-coverage-report-action/v2/dist/index.js:10:15[84](https://github.com/ePages-de/ng-merchant-ui/runs/5392613155?check_suite_focus=true#step:10:84)6)
    at ChildProcess.emit (node:events:3[90](https://github.com/ePages-de/ng-merchant-ui/runs/5392613155?check_suite_focus=true#step:10:90):28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
Switching back to original branch ended
```
I found the issue #199 which initially asked for the exact same feature. But in the end the solution only was to switched the branch back again, which causes issues with fork PRs.

### Alternatives

Do not fail on git errors.
Or switch back to the PR branch that the checkout action uses. This line is from the checkout step log of our workflow:
```
/usr/bin/git checkout --progress --force refs/remotes/pull/2475/merge
```

### Additional context

<details>
<summary>workflow file</summary>

```
      - name: Checkout
        uses: actions/checkout@v3
        # We need full history
        with:
          fetch-depth: 0

      - name: Get coverage cache
        uses: actions/cache@v2
        with:
          key: base-coverage-${{ github.ref }}
          restore-keys: base-coverage
          path: ./coverage/base-report.json

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
          cache: 'yarn'
      - name: Install project dependencies
        run: yarn --frozen-lockfile

      - name: Run linting
        run: yarn lint
      - name: Run tests
        run: yarn test --runInBand --coverage --coverageThreshold '{}' --testLocationInResults --json --outputFile=./coverage/report.json

      - uses: artiomtr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
          coverage-file: ./coverage/report.json
          base-coverage-file: ./coverage/base-report.json
          annotations: all
          skip-step: all
```
</details>
