### ISSUE TITLE
Paths included in `watchPathIgnorePatterns` are not ignored during CI

### ISSUE THREAD

**Issue by meloncatty** [ArtiomTr/jest-coverage-report-action#243]
### Describe a bug
Jest is configured in the `package.json` in my project:
```json
"jest": {
    "watchPathIgnorePatterns": [
      "src/__tests__/mockData",
      "src/__tests__/testHelpers",
      "src/__tests__/templates"
    ]
  }
```
These paths are ignored when running tests locally, but somehow they're picked up when using this GitHub action to run tests/collect coverage. Apologies if this was brought up previously but I couldn't find any related issues, opened or closed.

### Expected behavior

`watchPathIgnorePatterns` should be ignored during CI.

### Details

-   Action version: v2
-   OS, where your action is running: ubuntu-latest
-   action.yml file:
```yml
             - name: Run tests and collect coverage
                uses: ArtiomTr/jest-coverage-report-action@v2
                with:
                  skip-step: install
                  test-script: npm run test
```
-   Screenshots
        
![Console with a summary of a test suite failing because it does not contain tests](https://user-images.githubusercontent.com/11744547/156826659-7ab3b4ee-2ee0-4d44-bebb-ea5dbd6910d7.png)

### Additional context
[Configuring Jest](https://jestjs.io/docs/configuration)
I also tried with a `jest.config.js` file with no luck.
