### ISSUE TITLE
Generating report error - cannot convert undefined or null to object

### ISSUE THREAD

**Issue by ArtiomTr** [ArtiomTr/jest-coverage-report-action#244]
I am also having issues with the latest `v2.0.4` and I have a similar setup where I run jest and collect coverage in separate steps and then use `ArtiomTr/jest-coverage-report-action` for the annotations.

```yml
     - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: ./temp-coverage-results/current/jest.results.json
          base-coverage-file: ./temp-coverage-results/target/jest.results.json
          threshold: 80
          skip-step: all
          annotations: failed-tests
```

With `v2.0.4` it keeps failing with `TypeError: Cannot convert undefined or null to object` and I am not sure how to debug it.

![CleanShot 2022-03-04 at 13 46 25](https://user-images.githubusercontent.com/927264/156846352-11863af9-5f69-42a1-935c-8a8742e6e6a6.png)

---

Out of curiosity I tried to use `ArtiomTr/jest-coverage-report-action@Debug-action` instead (mentioned in another conversation) and with that particular version it works perfectly every time: branch in not switching, reports are being collected, annotation with coverage diffs is generated, etc..

I did some research but wasn't able to figure out where the `Debug-action` version comes from... is it based on an older version?! @ArtiomTr

_Originally posted by @raspo in https://github.com/ArtiomTr/jest-coverage-report-action/issues/242#issuecomment-1059559731_

**Comment by ArtiomTr** [comment]
Related: https://github.com/ArtiomTr/jest-coverage-report-action/issues/242#issuecomment-1059744737
> @raspo,
> 
> The `Debug-action` is not a version, it is a [branch](https://github.com/ArtiomTr/jest-coverage-report-action/tree/Debug-action). I created it from the `main` branch, so it should be the same as `v2.0.4` version, with few `console.log`'s added.
> 
> Looks like error occur on this line
> 
> https://github.com/ArtiomTr/jest-coverage-report-action/blob/9ce24ef8d37706be462dcd6128760ea7f1c1857b/src/format/summary/getSummary.ts#L11
> 
> The variable `map` is null or undefined. I don't know what could cause that issue, but it is definitely is not related to this one. I will create a separate issue for this.

**Comment by coelhucas** [comment]
I just faced this same (I believe) issue:

<img width="974" alt="image" src="https://user-images.githubusercontent.com/28108272/160136800-9b6071d7-bb4c-4dc6-82d8-cf626bd86535.png">

My first run was without any threshold, this was after adding it (not sure if it has relation, need further runs to check it)

**Comment by raspo** [comment]
@coelhucas what's your config? where you using version 2.0.5?
```uses: ArtiomTr/jest-coverage-report-action@v2.0.5```

**Comment by raspo** [comment]
I have also started to see this error on another repo I have been working on.
Like @lockettks I am also on `v2.05` and I am manually generating both reports.

```
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.0.5
        with:
          coverage-file: ./temp-coverage-results/current/coverage-final.json
          base-coverage-file: ./temp-coverage-results/target/coverage-final.json
          skip-step: all
          annotations: failed-tests
```

<img width="1004" alt="CleanShot 2022-04-12 at 09 39 41@2x" src="https://user-images.githubusercontent.com/927264/163012018-33ad1905-fef8-41ce-bfa3-a16ab589916d.png">

@ArtiomTr I'd be happy to help debug this, is there a branch or version of this action I can use that can help understand where exactly it is breaking? ideally one that isn't minimized? I think we should re-open this issue, btw.
