### ISSUE TITLE
Make option to pass timezone

### ISSUE THREAD

**Issue by ethanneff** [ArtiomTr/jest-coverage-report-action#25]
For example:

```
    "ci-test": "TZ=UTC jest -ci --forceExit --silent --coverage",
```

**Comment by ethanneff** [comment]
resolved

```
name: Jest Coverage
on:
  pull_request:
    branches:
      - master
jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      TZ: America/Los_Angeles
    steps:
      - uses: actions/checkout@v2
      - uses: artiomtr/jest-coverage-report-action@v1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

```
