### ISSUE TITLE
Action keeps running forever

### ISSUE THREAD

**Issue by ojuan19** [ArtiomTr/jest-coverage-report-action#251]
### Describe a bug

Hey folks, I'm trying to use the action but I have the following problem, after test have passed on `ArtiomTr/jest-coverage-report-action@v2`, action keeps running forever, I have to manually cancel it.

### Details

-   Action version: ArtiomTr/jest-coverage-report-action@v2
-   OS, where your action is running (windows, linux): Linux
-   <details><summary>action.yml file</summary>

        ```yml
        name: 'coverage'
        on:
          pull_request:
            types: [synchronize]
            branches:
              - master
              - main
         jobs:
          coverage:
            runs-on: ubuntu-latest
            steps:
              - name: Checkout code
                uses: actions/checkout@v1
              - name: Test coverage report
                uses: ArtiomTr/jest-coverage-report-action@v2
                with:
                  package-manager: yarn
                  test-script: yarn jest
        ```

    </details>

-   <details><summary>Screenshots</summary>

     
![jest coverage](https://user-images.githubusercontent.com/64972735/160413702-7a211f5d-4569-48f5-80cc-7ab92b82733f.png)

    </details>
