### ISSUE TITLE
I get the error: Coverage output file not found.

### ISSUE THREAD

**Issue by italoiz** [ArtiomTr/jest-coverage-report-action#254]
### Describe a bug

I'm trying to run the `jest-coverage-report-action` in my project, but I get error saying:

> Error: Coverage output file not found. (file "report.json" not found)

### Expected behavior

Execute a successful basic pipeline.

### Details

-   Action version: v2.0.5
-   OS, where your action is running (windows, linux): Linux
-   <details><summary>action.yml file</summary>

    ```yml
    name: 'Code Coverage'

    on:
      pull_request:
        paths-ignore:
          - 'docs/**'
        branches:
          - master
          - homol
        
    jobs:
      coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Test Coverage
            uses: ArtiomTr/jest-coverage-report-action@v2.0.5
            with:
              annotations: failed-tests
              github-token: ${{ secrets.GITHUB_TOKEN }}
              threshold: 90
    ```
    </details>

#### Screenshots

![image](https://user-images.githubusercontent.com/8454560/161086210-20037f68-9193-441d-9a8c-5f20f1fb88b8.png)
