### ISSUE TITLE
Error: HttpError: Bad credentials

### ISSUE THREAD

**Issue by kevalsavani** [ArtiomTr/jest-coverage-report-action#276]
Getting an error of `Error: HttpError: Bad credentials`, 

All the tests are run successfully, but I get an error when trying to publish the report. Is there anything wrong with my GitHub token, does it require any specific permission to publish the report?

Here is my runner file

**pull-request-coverage.yml**

```yml
name: Get Test Coverage
on:
  pull_request:
    branches:
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Get Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          package-manager: yarn
          test-script: yarn test:ci
          threshold: 60
```

**Runner failed** 

![image](https://user-images.githubusercontent.com/8718918/171208689-2d8025b8-55fc-4213-883a-ba7bb945acf4.png)

**Comment by ArtiomTr** [comment]
@kevalsavani,

Are you using this action in the private repo? If so, I think that your personal access token should also have permissions for that private repo. I recommend testing with GITHUB_TOKEN, it usually has all necessary privileges.

**Comment by kevalsavani** [comment]
Hi, @ArtiomTr when I use `GITHUB_TOKEN` in that case it works fine but then I get an error when I publish my package with the `npm publish` command in GitHub actions, although I have provided FULL permission to `PERSONAL_GITHUB_TOKEN` token which I am using while publishing package :/ 

![image](https://user-images.githubusercontent.com/8718918/171592687-0c24ab4a-b6c1-40aa-934b-dfcc42255fd1.png)

**Comment by ArtiomTr** [comment]
@kevalsavani,

Could you please attach full `yml` file with "publish" step? I think you can  use two different tokens - GITHUB_TOKEN for testing and PERSONAL_GITHUB_TOKEN for publishing.

**Comment by kevalsavani** [comment]
@ArtiomTr here is the full `yml` file, also wanted to know that `NODE_AUTH_TOKEN` should be from Github or from npmjs it self I am confused here, thanks 

```
name: Publish Node.js Package

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test:ci

      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
```
