### ISSUE TITLE
Cannot read properties of null (reading 'pickAlgorithm')

### ISSUE THREAD

**Issue by JohnieXu** [ArtiomTr/jest-coverage-report-action#284]
### Describe a bug

throw an Error `Cannot read properties of null (reading 'pickAlgorithm')`

### Expected behavior

no Error happened

### Details

-   Action version: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
-   OS, where your action is running (windows, linux): linux
-   <details><summary>action.yml file</summary>

      ```yml
      name: Node.js CI
      
      on:
        push:
          branches: [ master ]
        pull_request:
          branches: [ master ]
      
      jobs:
        test:
          runs-on: ubuntu-latest
      
          strategy:
            matrix:
              node-version: [10.x, 12.x, 14.x, 16.x]
      
          steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node-version }}
          - run: npm ci
          - run: npm run build
          - run: npm run lint
          - run: npm test
      
        coverage:
          needs: test
      
          runs-on: ubuntu-latest
      
          strategy:
            matrix:
              node-version: [16.x]
      
          steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
              node-version: ${{matrix.node-version}}
          - run: npm ci
          - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              test-script: npm run test:coverage
      ```

    </details>

-   <details><summary>Screenshots</summary>
- 
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/21156871/173176569-c7e16154-05f4-468f-bc5e-df63a253da1e.png">

    </details>

### Additional context

https://github.com/JohnieXu/decrypt-core/runs/6841442824?check_suite_focus=true

```bash
##[debug]/usr/bin/bash --noprofile --norc -e -o pipefail /home/runner/work/_temp/b7618da1-614b-4d8d-b551-5897cbcaffe4.sh
Running using node v16.15.1
Begin initialization stage...
Initialization stage ended
Begin head coverage collection...
Begin installing dependencies...
(node:1660) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
/opt/hostedtoolcache/node/16.15.1/x64/bin/npm install
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm ERR! Cannot read properties of null (reading 'pickAlgorithm')
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-06-11T06_13_43_429Z-debug-0.log
Installing dependencies failed
Error: Error: The process '/opt/hostedtoolcache/node/16.15.1/x64/bin/npm' failed with exit code 1
Installing dependencies ended
```
