### ISSUE TITLE
Doesn't keep .npmrc after switching branches

### ISSUE THREAD

**Issue by bmeverett** [ArtiomTr/jest-coverage-report-action#287]
### Describe a bug
When checking out the master branch to compare annotations, packages from private registries don't get installed.

### Expected behavior
Packages are able to be installed from private registries for the initial checkout as well as master.

### Details

-   Action version: v2
-   OS, where your action is running (windows, linux): ubuntu
-   <details><summary>action.yml file</summary>

        ```yml
        # Insert your action.yml file here. Don't forget to remove all sensitive information (e.g. tokens)
          name: 'code coverage'
          on:
              pull_request:
                  branches:
                      - master
                      - main
          jobs:
              coverage:
                  runs-on: ubuntu-latest
                  steps:
                      - uses: actions/checkout@v1
                      - name: Use Node.js 16.15.0
                        uses: actions/setup-node@v1
                        with:
                            node-version: 16.15.0
                      - name: Setup npmrc
                        run: printf "\n//npm.pkg.github.com/:_authToken=%s\n" ${{secrets.NPM_TOKEN}} >> ./.npmrc
                      - uses: ArtiomTr/jest-coverage-report-action@v2
                        with:
                            test-script: npm run test:cov
                            annotations: none 
                            annotations: none
        ```

    </details>

-   <details><summary>Screenshots</summary>

     
        
      ![Image 2022-06-22 at 14 46 22](https://user-images.githubusercontent.com/3941006/175113422-113a35ff-2c9a-45e0-91a9-eae8950709f1.png)
      ![Image 2022-06-22 at 14 48 13](https://user-images.githubusercontent.com/3941006/175113790-98d04571-60b5-4a47-9417-dd0dbf763f0d.png)

    </details>

### Additional context

This was working for awhile without any changes and just started to fail. Didn't change anything with my action. It still runs and "passes" but these errors are logged and it doesn't seem to be the correct behavior.
