### ISSUE TITLE
Feature Request: Overwrite coverage report comment when a test fails

### ISSUE THREAD

**Issue by blordpluto** [ArtiomTr/jest-coverage-report-action#289]
### Problem

When a commit causes a previously passing PR to fail a test, the old coverage comment remains. Since the default philosophy of the action seems to be to maintain and revise the coverage comment with the results of the latest run, it seems like it would make more sense to overwrite the comment with a message, something like:

> Coverage report not available due to failing test(s).

Not a big deal, but I think this would be a better developer experience than leaving the stale comment.

**Comment by ArtiomTr** [comment]
Hello @blordpluto :wave:,

Could you please attach your `action.yml` file and screenshots of comments and action's console? Or a link to a PR? Looks like a bug to me, action should overwrite the report comment by default, if tests fail.

**Comment by dalevfenton** [comment]
hello @ArtiomTr , not sure if I'm seeing exactly the same as described above, but I'm getting a new set of comments every time new commits are pushed to my PR. I've copied the job from our actions.yml as well as screenshots of the last 4 pushes that have each ended up with comments. Our actions run on `push` if the event matters.

The repo is private so I can't share it, but if you need more information please let me know.

This is the job in my `actions.yml`, we have a lerna monorepo and I have a matrix set up to run the tests in parallel in each package, it runs the tests and provides one comment for each package:

```
run_tests:
    name: Run Jest Tests
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        package-name: [package1, package2, package3]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Dependencies. // this just sets up node, yarn, installs packages and caches node_modules
        uses: ./.github/actions/setup
        with:
          npm-auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Run Tests and Comment
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: packages/${{ matrix.package-name }}
          test-script: yarn run test:ci
          package-manager: yarn
          skip-step: install
          annotations: failed-tests
```

below are screenshots from my last 4 pushes for one of the packages, (but each package is generating its own comment which is causing the PR to get really spammy):

![Screen Shot 2022-07-07 at 12 27 08 PM](https://user-images.githubusercontent.com/16996057/177824959-58d92842-189d-4376-a272-8836447ce40a.png)
