### ISSUE TITLE
Github permission documentation causes publication error

### ISSUE THREAD

**Issue by kevinvaningen** [ArtiomTr/jest-coverage-report-action#292]
### Describe a bug
I tried to get this plugin up and running. Caused me some time/delay.  One of the bigger hickups was the documentation on the permissions. With the 3 permissions in the docs my publish kept failing.

I needed to set the permission to  'contents: write' to get my build to succeed.

### Expected behavior

I expect that after following docs my permissions are set correctly. 

### Details

-   Action version: 2.08
-   OS, where your action is running (windows, linux): ubuntu standard github action runner
-   <details><summary>action.yml file</summary>

        ```yml

jobs:
  unit-test:
     runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v3

        

       some stuff omitted

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Test NPM test:unit
        run: |
          npm install -f
          npm run test:unit:coverage:ci

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.0.8
        with:
          skip-step: all
          coverage-file: ./test/unit/coverage/report.json
          base-coverage-file: ./test/unit/coverage/report.json
          github-token: ${{ secrets.GITHUB_TOKEN }}

        ```

    </details>

-   <details><summary>Screenshots</summary>
- <img width="1704" alt="shot error" src="https://user-images.githubusercontent.com/2325408/177589929-3d614dac-9dbd-4917-bbbb-a98d33f1766f.png">

    </details>
