### ISSUE TITLE
Multiple NPM Install errors, not working with Node 16.x

### ISSUE THREAD

**Issue by MorenoMdz** [ArtiomTr/jest-coverage-report-action#295]
### Describe a bug

Trying to have the report action work in our NestJS repository, tried many variations but those error when it gets to the NPM install steps.

### Details

-   Action version: Tried with 2.0rc4, rc6 and 2.0.8
-   OS, where your action is running (windows, linux): linux
-   <details><summary>action.yml file</summary>

        ```yml
        name: 'coverage'
          on:
            push:
          
          jobs:
            coverage:
              permissions:
                checks: write
                pull-requests: write
                contents: write
              runs-on: ubuntu-latest
              steps:
                - uses: actions/checkout@v2
                - uses: ArtiomTr/jest-coverage-report-action@v2.0.8
        ```
    

    </details>

### Additional context

Error example:

```
Run ArtiomTr/jest-coverage-report-action@v2.0.8
Run $GITHUB_ACTION_PATH/run.sh
Running using node v16.15.1
Begin initialization stage...
Initialization stage ended
Begin stages.parsethreshold...
stages.parseThreshold ended
Begin head coverage collection...
Begin installing dependencies...
/usr/local/bin/npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: traba-server-node@1.0.50
npm ERR! Found: @typescript-eslint/parser@5.14.0
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   dev @typescript-eslint/parser@"^5.8.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @typescript-eslint/parser@"^4.0.0" from @typescript-eslint/eslint-plugin@4.33.0
npm ERR! node_modules/@typescript-eslint/eslint-plugin
npm ERR!   dev @typescript-eslint/eslint-plugin@"^4.28.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/runner/.npm/eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-07-08T16_09_11_723Z-debug-0.log
Installing dependencies failed
Error: Error: The process '/usr/local/bin/npm' failed with exit code 1
Error: The process '/usr/local/bin/npm' failed with exit code 1
    at jp._setResult (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:10:17263)
    at jp.CheckComplete (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:10:1[68](https://github.com/trabapro/traba-server-node/runs/7254787340?check_suite_focus=true#step:3:68)53)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:10:15846)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
Installing dependencies ended
Begin running tests...
/usr/local/bin/npx jest --ci --json --coverage --testLocationInResults --outputFile=report.json
npm WARN exec The following package was not found and will be installed: jest
● Multiple configurations found:
    * /home/runner/work/traba-server-node/traba-server-node/jest.config.js
    * `jest` key in /home/runner/work/traba-server-node/traba-server-node/package.json
  Implicit config resolution does not allow multiple configuration files.
  Either remove unused config files or select one explicitly with `--config`.
  Configuration Documentation:
  https://jestjs.io/docs/configurati
Running tests failed
Error: Error: The process '/usr/local/bin/npx' failed with exit code 1
Error: The process '/usr/local/bin/npx' failed with exit code 1
    at jp._setResult (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:10:17263)
    at jp.CheckComplete (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:10:16853)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:10:15846)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
Running tests ended
Begin collecting coverage...
Loading code coverage from file: report.json
Collecting coverage failed
Error: Coverage output file not found. (file "report.json" not found)
Error: Coverage output file not found. (file "report.json" not found)
    at r5 (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:50:324)
    at async je (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:51:156)
    at async Fd (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:51:625)
    at async /home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:52:983
    at async je (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:51:156)
    at async Ow (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:52:948)
Collecting coverage ended
Begin parsing coverage...
Parsing coverage skipped
Parsing coverage ended
Head coverage collection failed
Error: Getting code coverage data failed.
Error: Getting code coverage data failed.
    at Fd (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:51:[76](https://github.com/trabapro/traba-server-node/runs/7254787340?check_suite_focus=true#step:3:77)0)
    at async /home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:52:983
    at async je (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:51:156)
    at async Ow (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:52:[94](https://github.com/trabapro/traba-server-node/runs/7254787340?check_suite_focus=true#step:3:96)8)
Head coverage collection ended
Begin switching to base branch...
Switching to base branch skipped
Switching to base branch ended
Begin base coverage collection...
Base coverage collection skipped
Base coverage collection ended
Begin switching back to original branch...
Switching back to original branch skipped
Switching back to original branch ended
Begin stages.checkthreshold...
stages.checkThreshold skipped
stages.checkThreshold ended
Begin generating report...
Generating report failed
Error: TypeError: Cannot read properties of undefined (reading 'success')
TypeError: Cannot read properties of undefined (reading 'success')
    at Km (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:49:289)
    at /home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:52:1515
    at je (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:51:162)
    at Ow (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.8/dist/index.js:52:1[47](https://github.com/trabapro/traba-server-node/runs/7254787340?check_suite_focus=true#step:3:49)7)
Generating report ended
Begin report publish...
Report publish skipped
Report publish ended
Begin failed tests' annotations publication...
Failed tests' annotations publication skipped
Failed tests' annotations publication ended
Begin coverage annotations publication...
Coverage annotations publication skipped
Coverage annotations publication ended
Error: Jest coverage report action failed
Error: Process completed with exit code 1.
```

One more error running with the example from the documentation:
```
Run npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: traba-server-node@1.0.50
npm ERR! Found: @typescript-eslint/parser@5.1[4](https://github.com/trabapro/traba-server-node/runs/7254890884?check_suite_focus=true#step:4:5).0
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   dev @typescript-eslint/parser@"^[5](https://github.com/trabapro/traba-server-node/runs/7254890884?check_suite_focus=true#step:4:6).8.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @typescript-eslint/parser@"^4.0.0" from @typescript-eslint/eslint-plugin@4.33.0
npm ERR! node_modules/@typescript-eslint/eslint-plugin
npm ERR!   dev @typescript-eslint/eslint-plugin@"^4.28.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/runner/.npm/eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-07-08T1[6](https://github.com/trabapro/traba-server-node/runs/7254890884?check_suite_focus=true#step:4:7)_16_59_8[7](https://github.com/trabapro/traba-server-node/runs/7254890884?check_suite_focus=true#step:4:8)[9](https://github.com/trabapro/traba-server-node/runs/7254890884?check_suite_focus=true#step:4:10)Z-debug-0.log
Error: Process completed with exit code 1.
```

This variation works if I used Node 14, but we need to test with Node 16
```
name: Jest Coverage
on: ['push']

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: User Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # - run: yarn install --frozen-lockfile

      - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by ArtiomTr** [comment]
Hello @MorenoMdz :wave:,

Firstly, I would recommend tweaking your configuration a bit. I see that you're using the `yarn` package manager, so it is better to set it up in action's options. In addition, it is better to use the `v2` version, as it will receive the latest patches without breaking changes. So, the configuration for this action should look like this:
```yml
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
```
Next, it looks like you don't have `jest` installed in your `package.json` file. Consider installing the latest version. Also, jest sees that you have two different configurations (one in `package.json` under the "jest" field, and one in the `jest.config.js` file). Jest doesn't know, which file to use, so you can either remove one configuration or overwrite the test script:
```yml
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
          test-script: yarn jest --config ./jest.config.js # or other path to the jest configuration file.
```
Hope these tweaks will fix your issue.

**Comment by MorenoMdz** [comment]
> Hello @MorenoMdz 👋,
> 
> Firstly, I would recommend tweaking your configuration a bit. I see that you're using the `yarn` package manager, so it is better to set it up in action's options. In addition, it is better to use the `v2` version, as it will receive the latest patches without breaking changes. So, the configuration for this action should look like this:
> 
> ```yaml
>       - uses: ArtiomTr/jest-coverage-report-action@v2
>         with:
>           github-token: ${{ secrets.GITHUB_TOKEN }}
>           package-manager: yarn
> ```
> 
> Next, it looks like you don't have `jest` installed in your `package.json` file. Consider installing the latest version. Also, jest sees that you have two different configurations (one in `package.json` under the "jest" field, and one in the `jest.config.js` file). Jest doesn't know, which file to use, so you can either remove one configuration or overwrite the test script:
> 
> ```yaml
>       - uses: ArtiomTr/jest-coverage-report-action@v2
>         with:
>           github-token: ${{ secrets.GITHUB_TOKEN }}
>           package-manager: yarn
>           test-script: yarn jest --config ./jest.config.js # or other path to the jest configuration file.
> ```
> 
> Hope these tweaks will fix your issue.

Hey there @ArtiomTr, thanks for the quick response!

The project has Jest and `ts-jest` in the dev dependencies in the `package.json` in the root folder, it is a NestJs project, as for the configuration, for some reason it was not finding the coverage settings when set in the `package.json` file so I tried adding a jest config file, but ill do some cleaning to have it in a single place.

Our current config without the coverage thresholds is this one, it runs fine with our other workflows atm. 

```
  "jest": {
    "moduleDirectories": [
      "node_modules",
      "src"
    ],
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "moduleNameMapper": {
      "^src/(.*)": "<rootDir>/$1"
    },
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
  ```

**Comment by MorenoMdz** [comment]
@ArtiomTr this is the message I get if I remove the jest config file:

```
Warning:  Failed to parse jest configuration. "coverageThreshold" from config file will be ignored. NoFilesFoundError: Could not resolve any file from the given array: /home/runner/work/traba-server-node/traba-server-node/jest.config.js, /home/runner/work/traba-server-node/traba-server-node/jest.config.ts, /home/runner/work/traba-server-node/traba-server-node/jest.config.mjs, /home/runner/work/traba-server-node/traba-server-node/jest.config.cjs, /home/runner/work/traba-server-node/traba-server-node/jest.config.json)
```

Tried using the base yml example with yarn, it does install it but it looks like there is some path issue going on:

<img width="1569" alt="image" src="https://user-images.githubusercontent.com/29472480/178117573-eaf00fa8-4aa4-4a7c-aef5-87207c4abc39.png">

**Comment by MorenoMdz** [comment]
Small update, got it to run with this workflow:

```
name: 'coverage'
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn

```
