### ISSUE TITLE
Unexpected input: prnumber

### ISSUE THREAD

**Issue by wimagguc** [ArtiomTr/jest-coverage-report-action#299]
### Describe a bug

Implemented the action as per the latest README:

```
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          prnumber: ${{ steps.findPr.outputs.number }}
```

...but when Github runs the action, we see a warning here:

```
Unexpected input(s) 'prnumber', valid inputs are ['github-token', 'test-script', 'threshold', 'working-directory', 'icons', 'annotations', 'package-manager', 'skip-step', 'custom-title', 'coverage-file', 'base-coverage-file']
```

...and sure enough, the PR isn't recognized, so the previous messages aren't deleted correctly either.

<img width="700" alt="example" src="https://user-images.githubusercontent.com/349687/180309432-30bd685e-305f-4d56-9430-3511a1482c01.png">

(`NOTE` that the PR number value would actually be correct, we can see the `prnumber: XX` value correctly printed to the console.)

### Expected behavior

The PR number is correctly used by the action.

### Details

-   Action version: `v2`
-   OS, where your action is running (windows, linux): `ubuntu-latest`
-   <details><summary>action.yml file</summary>

        ```yml
...
  coverage:
    needs: test
    permissions:
      checks: write
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v2
        with:
          name: coverage-report
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          prnumber: ${{ steps.findPr.outputs.number }}
          package-manager: yarn
          coverage-file: ./reports.json
          base-coverage-file: ./reports.json
          skip-step: all
          annotations: failed-tests
...
        ```

    </details>
