### ISSUE TITLE
Jest failed but step action success ?

### ISSUE THREAD

**Issue by abcfy2** [ArtiomTr/jest-coverage-report-action#302]
### Describe a bug

Here is the action snipped:

```yaml
      - name: test
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: src/main/javascript/crypto/
          test-script: npm run testjest
```

Full action yaml can be found in: https://github.com/TokenScript/attestation/blob/main/.github/workflows/js-p1.yml

Full action output can be found in: https://github.com/TokenScript/attestation/runs/7744484434?check_suite_focus=true

![image](https://user-images.githubusercontent.com/5327677/183636426-94256a52-96a6-4f3d-b1ac-e4fa9653989e.png)

You can see in fact `jest` was failed. But why this step is success after all ?

And annotation also not working after `test` step.

### Expected behavior

When jest failed, the step action should failed, and annotation should contains this fail message.

### Details

-   Action version: `v2`
-   OS, where your action is running (windows, linux): linux
-   <details><summary>action.yml file</summary>

        ```yml
          - name: test
            uses: ArtiomTr/jest-coverage-report-action@v2
            with:
              working-directory: src/main/javascript/crypto/
              test-script: npm run testjest
        ```

    </details>

-   <details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/5327677/183636426-94256a52-96a6-4f3d-b1ac-e4fa9653989e.png)

    </details>
