### ISSUE TITLE
Fatal github credentials

### ISSUE THREAD

**Issue by Juanma97** [ArtiomTr/jest-coverage-report-action#32]
When I push my changes, I receive this message in the execution of action:

/usr/bin/git fetch --all --depth=1
Fetching origin
fatal: could not read Username for 'https://github.com': No such device or address
error: Could not fetch origin
Error: The process '/usr/bin/git' failed with exit code 1

What is happen?

**Comment by yjcyun** [comment]
@Juanma97 Were you able to resolve this error? I'm getting the same message.

**Comment by derryl** [comment]
I'm also getting the same error. If anyone finds a solution here, I'd love to know!

**Comment by ArtiomTr** [comment]
I see that lot of people are facing same issue, but I have no idea, why this error occurs 😔
This is the line, causing the error ([link](https://github.com/ArtiomTr/jest-coverage-report-action/blob/736e53a60be639bd3f6c25c613296ab1a89acd8e/src/collect/getRawCoverage.ts#L22)). As you can see, this line fetches git repository, to get latest information about it. But this functionality is not necessary for this action. So, I'll try to just surround it with try / catch block and see, if it helps.

I'll try to fix it as soon as possible. Thank you for your patience.

**Comment by debajitr** [comment]
Thanks for the response @ArtiomTr, will be waiting for the fix 👍🏻

**Comment by ArtiomTr** [comment]
The problem was solved thanks to @atuttle (#40)

But, I will not release a new version for now, because currently, in master the new reporter for coverage is used, which isn't currently stable (#34). But, if you're facing this problem, you can use latest version with this configuration:

```yml
name: 'coverage'
on:
    pull_request:
        branches:
            - master
jobs:
    coverage:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v1
            # changes here                               \/
            - uses: artiomtr/jest-coverage-report-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
```

If you're using custom testing script, please note that with new version it should look like this:
```bash
npx jest --silent --ci --coverage --testLocationInResults --json --outputFile="report.json"
```
⚠I do not recommend to use master version all the time, so use it only if you're facing this issue. I'll let you know when the new version comes out.
