### ISSUE TITLE
Step fails where package dependencies have changed

### ISSUE THREAD

**Issue by jugory** [ArtiomTr/jest-coverage-report-action#333]
### Describe a bug

In the circumstance where my package.json has changed, I am finding that the switching between branches is failing due to changes in the yarn.lock

### Expected behaviour

This use case be handled

### Details

-   Action version: @v2
-   OS, where your action is running (windows, linux): linux
-   <details><summary>action.yml file</summary>

        ```yml
        name: Test meeting-state Template

        on:
          workflow_call:
            secrets:
              github-token:
                required: true
        
        permissions:
          id-token: write
          contents: read
          pull-requests: write
          checks: write
        
        jobs:
          deploy:
            runs-on: ubuntu-latest
            steps:
              - name: Git clone the repository
                uses: actions/checkout@v2
        
              - name: Install Node
                uses: actions/setup-node@v2
                with:
                  node-version: 16.x
        
              - name: Install root
                run: yarn
        
              - name: Test and coverage
                uses: ArtiomTr/jest-coverage-report-action@v2
                with:
                  package-manager: yarn
                  test-script: yarn test
                  github-token: ${{ secrets.github-token }}
        ```

    </details>

-   <details><summary>Screenshots</summary>

        ```
        Begin switching back to original branch...
        /usr/bin/git checkout -
        error: Your local changes to the following files would be overwritten by checkout:
	        yarn.lock
        Please commit your changes or stash them before you switch branches.
        Aborting
        Error checking to branches Error: The process '/usr/bin/git' failed with exit code 1
            at th._setResult (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:21:17898)
            at th.CheckComplete (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:21:17485)
            at ChildProcess.<anonymous> (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:21:16477)
            at ChildProcess.emit (node:events:513:28)
            at maybeClose (node:internal/child_process:1100:16)
            at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
        ```

    </details>

### Additional context

N/A
