### ISSUE TITLE
Annotations job attaches to a different workflow run

### ISSUE THREAD

**Issue by AlexLloyd0** [ArtiomTr/jest-coverage-report-action#338]
### Describe a bug

Annotations written by the action are executed in a different run to the one which triggered the tests. e.g. in the following screenshot, the `Test` workflow ran the coverage report. Then the jobs which attach checks run in an unrelated action.

This is confusing to devs - e.g. why is the "deploy" job attaching Coverage annotations?

### Expected behavior

Annotations are attached to the same workflow run.

### Details

Example:

AlexLloyd0/jest-coverage-report-action-bug-demo/pull/1

-   Action version: v2
-   OS: ubuntu-latest
-   <details><summary>action.yml file</summary>

        ```yml
          name: Test
          
          on:
            pull_request:
              branches:
                - '**'
          
          concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: true
          
          jobs:
            coverage:
              runs-on: ubuntu-latest
              permissions:
                checks: write
                pull-requests: write
                contents: read
              steps:
                - uses: 'actions/checkout@v3'
                - uses: actions/setup-node@v3
                  with:
                    node-version: '16'
          
                - uses: ArtiomTr/jest-coverage-report-action@v2
                  id: coverage
                  with:
                    package-manager: yarn
                    test-script: yarn test
        ```

    </details>

-   <details><summary>Screenshots</summary>

      ![example](https://user-images.githubusercontent.com/14766017/214249626-28535a4b-e5a8-4eaa-93d7-c6756decf868.png)

    </details>

### Additional context

Not sure if this is a bug in the action or a limitation in the GitHub checks API. Happy to look at fixing this, but may need a pointer
