### ISSUE TITLE
Istanbul ignore flags are being ignored

### ISSUE THREAD

**Issue by n0mbr3al3at0r10** [ArtiomTr/jest-coverage-report-action#342]
### Describe a bug

Istanbul ignore flags like `/* istanbul ignore next */` are being ignore, therefore the test coverage has statements not covered.

### Expected behavior

Istanbul flags should be taken into account and this action should return the same result as running the test locally.

### Details

-   Action version: 2.1.2
-   OS, where your action is running (windows, linux): linux
-   <details><summary>test.yml file</summary>

    ```yml
    name: test
    on: 
      pull_request:
        branches:
          - master
          - main
          - staging
    jobs:
      coverage:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3.3.0
          - name: 'Create env file'
            run: |
              echo "${{ secrets.ENV_FILE }}" > .env
          - uses: ArtiomTr/jest-coverage-report-action@v2.1.2
            id: coverage
            with:
              package-manager: yarn
              test-script: yarn jest
              output: report-markdown
          - uses: marocchino/sticky-pull-request-comment@v2.3.1
            with:
              message: ${{ steps.coverage.outputs.report }}
    ```
  
  </details>

-   <details><summary>Screenshots</summary>

        
    - GH Actions
    ![GitHub Actions](https://user-images.githubusercontent.com/86616429/216408206-323a4548-17d8-4fa2-af5d-412f8b6fb615.png)

    - Local
    ![Local](https://user-images.githubusercontent.com/86616429/216408662-4d31904a-5307-4672-90b0-5115b562d21d.png)

    </details>
