### ISSUE TITLE
Failing to generate test report after every run

### ISSUE THREAD

**Issue by ArmandAgopian** [ArtiomTr/jest-coverage-report-action#349]
### Describe a bug

Action fails to generate test report no matter what arguments are used. Multiple errors listed below.

### Expected behavior

The action displays coverage and test report separately

### Details

-   Action version: v2.2.1-rc.0
-   OS, where your action is running (windows, linux):
-   <details><summary>action.yml file</summary>

      ```
        - name: Find PR Number
           uses: jwalton/gh-find-current-pr@v1
           id: findPr
      
        - name: Jest coverage report
          uses: ArtiomTr/jest-coverage-report-action@v2.2.1-rc.0
          with:
            test-script: npm run test:ci
            prnumber: ${{ steps.findPr.outputs.number }}
      ```
</details>

-   <details><summary>jest:ci command w/ config</summary>

       `jest --runInBand --ci --json --testLocationInResults --outputFile=report.json`

       ```ts
        import type {Config} from 'jest';
        
        export default async (): Promise<Config> => {
          return {
            preset: 'ts-jest',
            testEnvironment: 'node',
            testTimeout: 1000,
            collectCoverageFrom: [
              'src/**/*.[jt]s'
            ],
            coveragePathIgnorePatterns: [
              'src/server/[jt]s'
            ],
            testMatch: [
              '**/?(*.)+(spec|test).[jt]s?(x)'
            ],
            collectCoverage: true,
            coverageThreshold: {
              global: {
                branches: 95,
                functions: 95,
                lines: 95,
                statements: 95
              },
            },
          };
        };
      ```
    </details>

-   <details><summary>Log File</summary>

        [Hastebin of error log](https://hastebin.com/share/ovohixuxug.yaml)

    </details>
