### ISSUE TITLE
HttpError: The patch could not be processed because too many files changed

### ISSUE THREAD

**Issue by amaljosea** [ArtiomTr/jest-coverage-report-action#353]
![Screenshot 2023-03-21 at 1 21 49 PM](https://user-images.githubusercontent.com/26934320/226546084-24f5fcdf-5adb-4777-96a0-ef9223249a4d.png)

```
    on:
      pull_request:
    jobs:
      coverage:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
          - uses: actions/checkout@v3
          - uses: ArtiomTr/jest-coverage-report-action@v2
            id: coverage
            with:
              output: report-markdown
              working-directory: frontend2
```
