### ISSUE TITLE
Error running jest-coverage-report-action

### ISSUE THREAD

**Issue by ocastx** [ArtiomTr/jest-coverage-report-action#358]
### Describe a bug

jest-coverage-report-action fails the GitHub action with error below even though tests work

### Expected behavior

Action runs successfully 

### Details

-   Action version: v2
-   OS, where your action is running (windows, linux): ubuntu linux
-   <details><summary>action.yml file</summary>
```yml
name: Pull Request
on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}_${{ github.action }}
  cancel-in-progress: true

jobs:
  CI:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Create npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          echo "@stikkyapp:registry=https://npm.pkg.github.com" >> .npmrc
      - name: Install
        run: yarn
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```
 </details>

-   <details><summary>Screenshots</summary>

<img width="1175" alt="CleanShot 2023-04-12 at 15 09 45@2x" src="https://user-images.githubusercontent.com/2399622/231467670-7021c4d3-b083-4829-b5d8-78fe297cc4ee.png">

    </details>
