### ISSUE TITLE
threshold input doesn't seem to actually reject a PR

### ISSUE THREAD

**Issue by hyperair** [ArtiomTr/jest-coverage-report-action#361]
### Describe a bug

I'm running the GH action on jest report json files generated in a separate step like so:

```yaml
      - name: Report coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          annotations: failed-tests
          skip-step: all
          coverage-file: report.json
          base-coverage-file: base-report.json
          threshold: 45
```

In the comment posted by `jest-coverage-report-action`, I see that it does indeed report that the coverage doesn't meet the threshold, but I can't find any indication of the PR being rejected, nor can I spot any code in the GH action that does it. How is this supposed to work?

### Expected behavior

On coverage falling below the threshold, I'm expecting a failed status check that can be used together with Github's branch protection required status checks, but it looks like all steps in the workflow have succeeded.

### Details

-   Action version: v2
-   OS, where your action is running (windows, linux): linux
-   <details><summary>action.yml file</summary>

    ```yml
          - name: Report coverage
            uses: ArtiomTr/jest-coverage-report-action@v2
            with:
              annotations: failed-tests
              skip-step: all
              coverage-file: report.json
              base-coverage-file: base-report.json
              threshold: 45
    ```

    </details>

-   <details><summary>Screenshots</summary>

    ![image](https://user-images.githubusercontent.com/88355/233357728-f0010c32-5386-4a9c-866b-136d83b987a3.png)

    </details>

**Comment by momenthana** [comment]
Since I'am using vitest, I conducted the test from the lowest version where json reporter can be used.
In versions that meet this, we have verified that the guard only works in v2.0-rc.4.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/59823089/234874656-f9b9b539-7342-4f13-9ea6-eed375c0a5b9.png">

<details><summary>action.yml file</summary>

```yml

name: Test Coverage Report

on:
  pull_request:
    branches: '**'

jobs:
  CI:
    permissions:
      checks: write
      pull-requests: write
      contents: write 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          path: base 
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Test base coverage report
        working-directory: base
        run: |
          yarn
          yarn test:coverage --reporter json --outputFile ./coverage/report.json || true && node ./__tests__/save-coverage-file.js
      
      - name: Test coverage report
        run: |
          yarn
          yarn test:coverage --reporter json --outputFile ./coverage/report.json || true && node ./__tests__/save-coverage-file.js
        
      - name: Test coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.4
        with:
          github-token: ${{ github.token }}
          skip-step: all
          threshold: 50
          coverage-file: ./coverage/report.json
          base-coverage-file: ./base/coverage/report.json

```
</details>

**Comment by momenthana** [comment]
I can see the report well, so it's the most ideal version I'm currently using...

<img width="908" alt="image" src="https://user-images.githubusercontent.com/59823089/234875534-62a94366-ed5d-40d4-b881-cc8bc45d0fcf.png">

I hope it will improve in the upper version as well.

**Comment by momenthana** [comment]
First, I considered using both versions together temporarily to use more mature annotations.

```yml
      - name: Test coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ github.token }}
          skip-step: all
          threshold: 60
          coverage-file: ./coverage/report.json
          base-coverage-file: ./coverage/base-report.json

      - name: Test coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.4
        with:
          github-token: ${{ github.token }}
          skip-step: all
          threshold: 60
          coverage-file: ./coverage/report.json
          base-coverage-file: ./coverage/base-report.json
          annotations: none
          output: report-markdown
```
