### ISSUE TITLE
Stuck on npm install

### ISSUE THREAD

**Issue by drilonibrahimi** [ArtiomTr/jest-coverage-report-action#368]
### Describe a bug

Hi @ArtiomTr,

I'm facing this issue where the action script is not working as expected, it's getting stucked on `npm install`! Please see the attached images. 

Any hints on why is this happening?

### Details

-   Action version: v2
-   OS, where your action is running (windows, linux):  ubuntu_latest
-   <details><summary>action.yml file</summary>

        ```
            steps:
                    - name: Checkout this repo
                      uses: actions/checkout@v3
                      
                    - name: Generate coverage report
                        uses: artiomtr/jest-coverage-report-action@v2
                        with:
                            github-token: *

        ```

    </details>

-   <details><summary>Screenshots</summary>

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/39486900/235192637-c3931831-c0f0-4674-9ab8-1b85e09e9a37.png">

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/39486900/235192857-b07b8880-c9a4-4992-9236-91a82ad5888c.png">

    </details>

**Comment by drilonibrahimi** [comment]
Update 1) 

13 mins with no response, I had to cancel the job since either way we can't have this take any longer than 1-2 mins.

**Comment by ArtiomTr** [comment]
Hello @drilonibrahimi :wave:,

Looks like this is an issue with npm. Maybe it is related to the old npm version, can you please try to bump the NodeJS version (or just npm), like so:

```yaml
    steps:
            - name: Checkout this repo
              uses: actions/checkout@v3
              
            - name: Setup NodeJS 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Setup npm 9.6.5
              run: corepack enable && corepack prepare npm@9.6.5 --activate

            - name: Generate coverage report
              uses: artiomtr/jest-coverage-report-action@v2
              with:
                  github-token: *

```

If it doesn't work, you can try to apply the fixes described [here](https://stackoverflow.com/questions/16873973/npm-install-hangs).
