### ISSUE TITLE
PRs that don't change tests showing a change in coverage

### ISSUE THREAD

**Issue by carusooo** [ArtiomTr/jest-coverage-report-action#369]
### Describe a bug

PRs that don't change tests at all are showing a change in coverage. 

1. I make a change to a README.md file
2. Upload the PR 
3. The coverage shows changes between 2-15%

### Expected behavior

No changes to coverage should be displayed.

### Details

-   Action version: v2
-   OS: linux
-   <details><summary>action.yml file</summary>
 
      ```yml
      name: Pull Request - Backend
      on:
        pull_request:
          paths:
            - "backend/**"
      
      defaults:
        run:
          working-directory: backend
      
      jobs:
        lint-and-test:
          runs-on: ubuntu-20.04
          env:
            MODE: CI
      
          steps:
            - name: checkout
              uses: actions/checkout@v2
      
            - name: install node.js
              uses: actions/setup-node@v1
              with:
                node-version: 16.x
      
            - name: install node packages
              run: npm install
      
            - name: run lint
              run: npm run lint
      
            - uses: ArtiomTr/jest-coverage-report-action@v2
              id: coverage
              with:
                working-directory: backend
                github-token: ${{ github.token }}
                output: report-markdown
                annotations: none
            - uses: marocchino/sticky-pull-request-comment@v2
              with:
                message: ${{ steps.coverage.outputs.report }}
      
            - name: ensure clean working directory
              run: |
                rm report.json
                if files=$(git ls-files --exclude-standard --others --modified) && [[ -z "$files" ]]; then
                  exit 0
                else
                  echo ""
                  echo "Working directory has been modified:"
                  echo ""
                  git status --short
                  echo ""
                  exit 1
                fi
        build:
          runs-on: ubuntu-20.04
          steps:
            - name: checkout
              uses: actions/checkout@v2
      
            - name: install node.js
              uses: actions/setup-node@v1
              with:
                node-version: 16.x
      
            - name: install node packages
              run: npm install
      
            - name: run build
              run: npm run build        
      ```

    </details>

-   <details><summary>Screenshots</summary>
      
      
      
      ## Coverage report for `backend`
      
      
      
      | <div title="Status of coverage:&#10; 🟢 - ok&#10; 🟡 - slightly more than threshold&#10; 🔴 - under the threshold">St.<sup>:grey_question:</sup></div> | Category   | Percentage                                                     | Covered / Total |
      | :----------------------------------------------------------------------------------------------------------------------------------------------------: | :--------- | :------------------------------------------------------------- | :-------------: |
      |                                                                           🔴                                                                           | Statements | <div title="Base coverage is: 36.9%">45.89% (+8.99% 🔼)</div>  |    1241/2704    |
      |                                                                           🔴                                                                           | Branches   | <div title="Base coverage is: 17.9%">32% (+14.1% 🔼)</div>     |     136/425     |
      |                                                                           🔴                                                                           | Functions  | <div title="Base coverage is: 31.83%">36.25% (+4.42% 🔼)</div> |     141/389     |
      |                                                                           🔴                                                                           | Lines      | <div title="Base coverage is: 42.94%">44.99% (+2.05% 🔼)</div> |    1154/2565    |
      
      
      ## Test suite run success
      88 tests passing in 27 suites.
      
      <p align="right">Report generated by <a href="https://github.com/ArtiomTr/jest-coverage-report-action">🧪jest coverage report action</a> from 68938ffdb6cf7e29a6cef298820e83482370bb2a</p>
      
      
    </details>

### Additional context

The above output is generated based on a change to a README.md file (not used in tests). The repository uses squash-merge commits.
