### ISSUE TITLE
Is it possible to run test coverage without installing node modules 

### ISSUE THREAD

**Issue by yogeshrathodd** [ArtiomTr/jest-coverage-report-action#37]
I have already installed all the node modules in before running test coverage so can we skip the node module installation part

**Comment by ArtiomTr** [comment]
Currently, there is no way to do this. Similar functionality is also required for (#20), so I'll try to combine those features into one PR. 

At the moment I am not closing this issue, so you can follow the development of this feature

**Comment by ArtiomTr** [comment]
This issue as well as #20 was resolved thanks to @taschetto!

For now, until version 2.0 was released, you can try it by using `@master` version with this configuration:
```yml
name: 'coverage'
on:
    pull_request:
        branches:
            - master
jobs:
    coverage:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v1
            - uses: artiomtr/jest-coverage-report-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  skip-step: all
```
