### ISSUE TITLE
stages.checkThreshold failed

### ISSUE THREAD

**Issue by himanshu-leap** [ArtiomTr/jest-coverage-report-action#377]
### Describe a bug
I have added a `coverageThreshold` value to 0, but still `stages.checkThreshold` is failing

```
// package.json
{
   ...
     "jest": {
     ...
    "coverageThreshold": {
      "global": {
        "lines": 0
      }
    }
  }
}
```

```
// workflow
- name: 📝 Coverage Report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: ./apps/extension/coverage/coverage-final.json
          base-coverage-file: ./apps/extension/coverage/coverage-final.json
```

<img width="870" alt="Screenshot 2023-06-11 at 1 56 49 PM" src="https://github.com/ArtiomTr/jest-coverage-report-action/assets/110231645/baba8482-63ab-4896-b57e-20b07a037a94">
