### ISSUE TITLE
stages.checkThreshold failed

### ISSUE THREAD

**Issue by hsnice16** [ArtiomTr/jest-coverage-report-action#378]
### Describe a bug
I have added a `coverageThreshold` value to 0, but still `stages.checkThreshold` is failing

```
// package.json
{
   ...
     "jest": {
     ...
    "coverageThreshold": {
      "global": {
        "lines": 0
      }
    }
  }
}
```

```
// workflow
- name: 📝 Coverage Report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: ./apps/extension/coverage/coverage-final.json
          base-coverage-file: ./apps/extension/coverage/coverage-final.json
```

<img width="870" alt="Screenshot 2023-06-11 at 1 56 49 PM" src="https://github.com/ArtiomTr/jest-coverage-report-action/assets/110231645/baba8482-63ab-4896-b57e-20b07a037a94">

**Comment by osnoser1** [comment]
Hi, same problem too!
<img width="839" alt="image" src="https://github.com/ArtiomTr/jest-coverage-report-action/assets/1179744/23a6e737-2a42-4ead-ba5b-b6fd9e80b051">

```
      - name: Publish coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          skip-step: all
          coverage-file: ./coverage/coverage-final.json
          base-coverage-file: ./coverage/coverage-final.json
```

**Comment by thierryVerrier** [comment]
Hi, same problem too!

**Comment by AjaSharma93** [comment]
Same problem here.

**Comment by devinekadeni** [comment]
I also experiencing this, any update about this? @ArtiomTr

**Comment by devinekadeni** [comment]
UPDATE:
after debugging on the source code turns out the problem was the generated coverage file have no `coverageMap` property.
This thread would explain everything https://github.com/ArtiomTr/jest-coverage-report-action/issues/244#issuecomment-1097360277.
Now it works on my side

**Comment by alisweatworks** [comment]
> UPDATE: after debugging on the source code turns out the problem was the generated coverage file have no `coverageMap` property. This thread would explain everything [#244 (comment)](https://github.com/ArtiomTr/jest-coverage-report-action/issues/244#issuecomment-1097360277). Now it works on my side

Hi @devinekadeni! I'm facing the same issue here. can you specify how did you make it work on your side?

**Comment by devinekadeni** [comment]
> > UPDATE: after debugging on the source code turns out the problem was the generated coverage file have no `coverageMap` property. This thread would explain everything [#244 (comment)](https://github.com/ArtiomTr/jest-coverage-report-action/issues/244#issuecomment-1097360277). Now it works on my side
> 
> Hi @devinekadeni! I'm facing the same issue here. can you specify how did you make it work on your side?

@alisweatworks  this is what I did on my workflow file

```yaml
- name: Run test with coverage
   run: npm run test:coverage -- --json --outputFile="coverage/coverage-report.json"

- uses: ArtiomTr/jest-coverage-report-action@v2
   with:
     skip-step: all
     annotations: none 
     coverage-file: coverage/coverage-report.json
     base-coverage-file: coverage/coverage-report.json
```

```json
// package.json
...
"scripts": {
    "test:coverage": "jest --coverage",
}
...
```
