### ISSUE TITLE
Getting error after running the test script - Error: ❌ Output of test script has invalid format. Check [documentation](https://github.com/ArtiomTr/jest-coverage-report-action#jest-coverage-report-) for more details.

### ISSUE THREAD

**Issue by sharmapuneet** [ArtiomTr/jest-coverage-report-action#38]
This is how I've implemented my workflow file -

```
on: pull_request

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Comment with Test Coverage
        uses: artiomtr/jest-coverage-report-action@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          test_script: npm run test --silent --ci --coverage --json --coverageReporters="text" --coverageReporters="text-summary" --outputFile=\"report.json\"
```

**Comment by sharmapuneet** [comment]
This is how I've implemented my workflow file -
`on: pull_request

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Comment with Test Coverage
        uses: artiomtr/jest-coverage-report-action@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          test_script: npm run test --silent --ci --coverage --json --coverageReporters="text" --coverageReporters="text-summary" --outputFile=\"report.json\"
`

**Comment by ArtiomTr** [comment]
Your test script returns data in invalid format. Consider using this test script:
```bash
npm run test --silent --ci --coverage --coverageReporters="text" --coverageReporters="text-summary"
```

**Comment by sharmapuneet** [comment]
I tried using the above script still getting the same error. 
<img width="1057" alt="Screen Shot 2021-06-05 at 11 39 42 AM" src="https://user-images.githubusercontent.com/1584624/120876214-d7e81200-c5f2-11eb-958f-7be572146cca.png">

**Comment by ArtiomTr** [comment]
Could you take please a full screenshot of the console output? Now, I can't see what your script outputs, and I can't figure out what the problem is. I would also like to ask which version of Jest are you using?

Also, can you try please to not specify custom testing script, so your action will look like:
```yml
on: pull_request

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Comment with Test Coverage
        uses: artiomtr/jest-coverage-report-action@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
