### ISSUE TITLE
False-positive fail check

### ISSUE THREAD

**Issue by seahindeniz** [ArtiomTr/jest-coverage-report-action#383]
### Describe a bug

After tests gets failed and rerun again, previous report doesn't get cleaned up
<img width="25%" src="https://github.com/ArtiomTr/jest-coverage-report-action/assets/5789670/26c1cac9-59e8-41f8-8cd4-d695bcde80a2">

### Expected behavior

I expect, re-running a failed check should always remove the previous report, and report a new one for a new failure or report none for a success case.
<img width="25%" src="https://github.com/ArtiomTr/jest-coverage-report-action/assets/5789670/bd768cff-1908-4f48-9180-b47b9ea29409">

### Details

-   Action version:
-   OS, where your action is running (windows, linux): Linux

<details>
<summary>action.yml file</summary>

```yml
name: "Run Tests"

on:
  push:
  schedule:
    - cron: "00 10,15 * * *"

concurrency:
  group: testing-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: self-runner-node
    timeout-minutes: 10
    permissions:
      checks: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci --loglevel=error --no-fund --no-audit

      - name: Run tests
        id: test
        run: npm test -- --runInBand --ci --json --coverage --testLocationInResults --outputFile=report.json

      - name: Find PR
        if: always() && startsWith(github.ref, 'refs/heads/feature/')
        uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: Report results for feature branch
        if: always() && startsWith(github.ref, 'refs/heads/feature/')
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          skip-step: all
          coverage-file: report.json
          base-coverage-file: report.json
          output: comment
          prnumber: ${{ steps.findPr.outputs.number }}

      - name: Report results for master branch
        if: always() && github.ref == 'refs/heads/master'
        uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverageForMaster
        with:
          skip-step: all
          coverage-file: report.json
          base-coverage-file: report.json
          output: report-markdown
          annotations: failed-tests

      - name: Open issue
        if: failure() && github.ref == 'refs/heads/master' && steps.test.conclusion == 'failure'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          testOutput: ${{ steps.coverageForMaster.outputs.report }}
        with:
          filename: .github/tests-failed.md
```
</details>

<details><summary>Screenshots</summary>

        

        

    </details>
