### ISSUE TITLE
Generating report failed with TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by QuentinLemCode** [ArtiomTr/jest-coverage-report-action#388]
### Describe a bug

Hello,
The action fail on main branches while it works on PR.
See the screenshot below and the report.json gist link

### Expected behavior

The report is generated and a comment is added to the PR

### Details

-   Action version: latest
-   OS, where your action is running (windows, linux): linux
-   <details><summary>action.yml file</summary>

        ```yml
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - name: Run Tests
        run: npm run test:ci
      - name: Save coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage
          retention-days: 1
      - name: Publish Coverage
        uses: artiomtr/jest-coverage-report-action@f1a1382101d9b92b38e3df05c9ed89a834af97c8
        with:
          coverage-file: ./coverage/report.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 90
          annotations: coverage
          skip-step: all
        ```

    </details>

-   <details><summary>Screenshots</summary>
![image](https://github.com/ArtiomTr/jest-coverage-report-action/assets/3814031/6dfb9a08-e1bd-4143-b92e-b71d691192b6)
![image](https://github.com/ArtiomTr/jest-coverage-report-action/assets/3814031/089cea92-6ee6-4c32-a925-bcbe2a5e4930)
https://gist.github.com/QuentinLemCode/3600641d8b3db7c6c5753c1896ce9224
    </details>

**Comment by ArtiomTr** [comment]
Hello @QuentinLemCode 👋,

Looks like the coverage file `coverage/report.json` has an invalid format. Please make sure you're generating a coverage file with the necessary flags: https://github.com/ArtiomTr/jest-coverage-report-action#customizing-test-script

**Comment by QuentinLemCode** [comment]
@ArtiomTr Thanks for reply
I don't see what's wrong with my report.json file. 
Also the jest command line is the same in than in other branches, but it fail only on main. 
Can you take a look at the gist?

**Comment by ArtiomTr** [comment]
Try to specify:
```yaml
        with:
          coverage-file: ./coverage/report.json
          base-coverage-file: ./coverage/report.json # this line added
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 90
          annotations: coverage
          skip-step: all
```
This will skip coverage comparison. This is not ideal, but at least your CI will work for now. I need more time to dig deeper into this issue

**Comment by M-Schiller** [comment]
Did you find to look deeper into this yet? Just now, I could observe the same behavior:

```yaml
jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ArtiomTr/jest-coverage-report-action@v2.3.0
        with:
          package-manager: yarn
          output: comment, report-markdown
          icons: emoji
          threshold: 80
```

The code above runs perfectly fine on PRs but breaks on `main`:

```
Begin generating report...
Generating report failed
Error: TypeError: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at hu (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.3.0/dist/index.js:2107:5062)
    at d1 (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.3.0/dist/index.js:2107:5229)
    at b1 (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.3.0/dist/index.js:2116:35)
    at g9 (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.3.0/dist/index.js:2133:336)
    at /home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.3.0/dist/index.js:2145:15890
    at wr (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.3.0/dist/index.js:2136:164)
    at LN (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.3.0/dist/index.js:2145:15852)
Generating report ended
Begin report publish...
Report publish skipped
Report publish ended
Begin setting outputs...
Setting outputs skipped
Setting outputs ended
Begin failed tests' annotations publication...
Failed tests' annotations publication failed
Error: TypeError: Cannot read properties of undefined (reading 'runReport')
TypeError: Cannot read properties of undefined (reading 'runReport')
    at /home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.3.0/dist/index.js:2145:16426
    at wr (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.3.0/dist/index.js:2136:164)
    at LN (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.3.0/dist/index.js:2145:16270)
Failed tests' annotations publication ended
```

**Comment by imphatic** [comment]
really want to use this but no matter what combination of configs I use i always get the "Error: TypeError: Cannot convert undefined or null to object" as outlined in this issue.

**Comment by rsorelli-hedgepoint** [comment]
Hi there, 

Today I got the same issue and it seems to be related with the "threshold" flag.
When I ran the action setting the threshold and I do not met it the coversion error occours.
However, it the project passed the threshold the action completes "OK".

`      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.3.1
        with: 
          skip-step: install
          working-directory: ${{ matrix.test_dir }}
          annotations: coverage
          threshold: 80
`

**Comment by joeteerawit** [comment]
Use following command to run test before using `ArtiomTr/jest-coverage-report-action@v2` work for me
```
      - name: Run Test
        run: npx jest --ci --json --coverage --testLocationInResults --outputFile=report.json
```

all config

```
      - name: Unit Test
        run: npx jest --ci --json --coverage --testLocationInResults --outputFile=report.json
      
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
           prnumber: ${{ steps.findPr.outputs.number }}
           skip-step: all
           threshold: 75
```
