### ISSUE TITLE
Coverage report is running but getting a git issue "could not read Username for https://github.com"

### ISSUE THREAD

**Issue by atuttle** [ArtiomTr/jest-coverage-report-action#39]
As you can see in the attached screen shot, the coverage report seems to run just fine. My best guess is that it's failing when trying to switch to the main branch for the comparison report.

For what it's worth, this is a new project in the repo so the entire folder doesn't exist in the head branch. Not sure if that could cause it.

![image](https://user-images.githubusercontent.com/46990/120861464-57270880-c555-11eb-8585-2d6f147b395c.png)

My action YAML is pretty basic:

```yml
name: Deferred Click Logger Lambda Tests
on:
  push:
    branches:
      - main
      - qa
  pull_request:
    branches:
      - main
    paths:
      - 'lambda/ClickLogger/**'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: artiomtr/jest-coverage-report-action@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: lambda/ClickLogger
          #   threshold: 80 # optional parameter
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: test
        run: npm ci && npm run test
```
