### ISSUE TITLE
Cannot checkout branch from private fork

### ISSUE THREAD

**Issue by ddlan** [ArtiomTr/jest-coverage-report-action#393]
### Describe a bug

When raising a PR to a repo from a private fork, the github action fails when trying to check out the PR branch because it does not have access to the private remote.

### Expected behavior

The github action should be able to check out the PR HEAD commit by hash and run test coverage.

### Details

-   Action version: v2.2.4
-   OS, where your action is running (windows, linux): linux
-   <details><summary>action.yml file</summary>

```yml
name: Coverage report
on:
  pull_request:
    branches:
      - master
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          git fetch --no-tags --depth=1 origin master
          git checkout -b master
          git checkout ${{ github.event.pull_request.head.sha }}
      - uses: ArtiomTr/jest-coverage-report-action@v2.2.4
        with:
          package-manager: yarn
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./webserver
          test-script: yarn jest --changedSince=master --silent
 ```

    </details>

-   <details><summary>Screenshots</summary>

<img width="838" alt="image" src="https://github.com/ArtiomTr/jest-coverage-report-action/assets/25760929/cf7695ad-c9fa-434b-a3e5-6f021867edf3">
<img width="740" alt="image" src="https://github.com/ArtiomTr/jest-coverage-report-action/assets/25760929/1b092799-294c-42f5-aaad-b05a550dd4ca">

    </details>
