### ISSUE TITLE
Unchanged files with check annotations (beta)

### ISSUE THREAD

**Issue by VictorComette** [ArtiomTr/jest-coverage-report-action#405]
### Describe a bug

I'm unable to prevent coverage annotation on unchanged files. I've setup the action with `annotations: coverage` and expected to have annotations to changed files only, as stated in the docs:

> coverage - Will annotate those sections of your code that test did not cover. Limited to changed lines when used on a Pull Request

Even so, GH is adding a entire section on the diff entitled "Unchanged files with check annotations (beta)" with a bunch of annotations.

As we are starting a long effort of covering a huge legacy application with tests, this is becoming an issue due to the extensive number of files without coverage. 

### Expected behavior

To have coverage annotations on changed files only (changed lines if possible).

### Details

-   Action version: v2.2.4
-   OS, where your action is running (windows, linux): linux (ubuntu)
-   <details><summary>action.yml file</summary>

        ```yml
        name: Build and Test
        
        on:
          workflow_call:
            secrets: ...
            ...
            
         jobs:
           build-and-test:
           ...
             - name: Test
                id: test
                run:  npm run test:coverage:ci
                # jest --verbose --ci --coverage --json --testLocationInResults --outputFile=report.json
        
              - name: Find Current Pull Request
                id: findPr
                uses: jwalton/gh-find-current-pr@v1.3.2
        
              - name: Report Test Coverage
                uses: ArtiomTr/jest-coverage-report-action@v2.2.4
                with:
                  prnumber: ${{ steps.findPr.outputs.number }}
                  annotations: coverage
                  coverage-file: report.json
                  base-coverage-file: report.json
        ```

    </details>

-   <details><summary>Screenshots</summary>

        ![image](https://github.com/ArtiomTr/jest-coverage-report-action/assets/92056348/b9d4180e-83df-4886-8c70-a35b57ecc0f5)

    </details>
