### ISSUE TITLE
Emojis is not displayed on OSX Mojave (10.14)

### ISSUE THREAD

**Issue by ArtiomTr** [ArtiomTr/jest-coverage-report-action#41]
Previous screen shot is Vivaldi on OSX Mojave (10.14).

Here's the latest Firefox on the same OSX:

![image](https://user-images.githubusercontent.com/46990/121043671-d5b4bd80-c782-11eb-958b-6f8eeb6f06e0.png)

And the latest Chrome on the same OSX:

![image](https://user-images.githubusercontent.com/46990/121043776-efee9b80-c782-11eb-8544-50ac52a0aff8.png)

_Originally posted by @atuttle in https://github.com/ArtiomTr/jest-coverage-report-action/issues/32#issuecomment-856033224_

**Comment by ArtiomTr** [comment]
This issue can appear not only on OSX Mojave, so in my opinion, `jest-coverage-report-action` should have an option to choose 
which icons to use. For example:
```yml
name: 'coverage'
on:
    pull_request:
        branches:
            - master
jobs:
    coverage:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v1
            - uses: artiomtr/jest-coverage-report-action@v1.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
#                         ↓
                  icons: emoji
```

Another option would be to use ASCII characters instead of emojis.

**Comment by ArtiomTr** [comment]
Created new option `icons`, usage:

```yml
name: 'coverage'
on:
    pull_request:
        branches:
            - master
jobs:
    coverage:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v1
            - uses: artiomtr/jest-coverage-report-action@v1.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
#                         ↓
                  icons: unicode
```

Currently available using `@master` version.

Examples of generated reports with different icons could be found here #42
