### ISSUE TITLE
[Bug] UI Bug where Status column name is not coming correctly.

### ISSUE THREAD

**Issue by ab14bhardwaj** [ArtiomTr/jest-coverage-report-action#419]
### Describe a bug

- UI Bug where the Status column name is not coming correctly.
The same issue is there in the screenshots attached in the readme file.
 
<img width="402" alt="Screenshot 2024-03-06 at 10 36 25 PM" src="https://github.com/ArtiomTr/jest-coverage-report-action/assets/110031935/db8f8645-c671-4520-b397-a44e29ac0b3d">

### Expected behaviour

<img width="425" alt="Screenshot 2024-03-06 at 10 34 46 PM" src="https://github.com/ArtiomTr/jest-coverage-report-action/assets/110031935/b0dd3880-96f5-4a94-ab8d-388513741fe0">

### Details

-   Action version: ```ArtiomTr/jest-coverage-report-action@v2```
-   OS, where your action is running (windows, linux): ```macOS```
-   YML File
```
name: 'Coverage' # Name of your GitHub Actions workflow

jobs:
  coverage:
    runs-on:
      - self-hosted

    steps:
      - name: Checkout code # Step to checkout the repository's code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run coverage report # Step to run the coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn # Specify the package manager being used (optional)
          test-script: yarn run test:ci # Specify the test script to generate coverage report
          custom-title: Billing Coverage Report # Specify a custom title for the coverage report (optional)
```
