### ISSUE TITLE
Tests run 2 times instead of 1

### ISSUE THREAD

**Issue by piotrwalczak1** [ArtiomTr/jest-coverage-report-action#425]
### Describe a bug
Why the tests run 2 times in a row instead of 1?
![image](https://github.com/ArtiomTr/jest-coverage-report-action/assets/95431451/71292487-e1ea-4152-93aa-deb992e4c489)

Then it's running it for the 2nd time?
![image](https://github.com/ArtiomTr/jest-coverage-report-action/assets/95431451/4e6c45d4-ebdd-4d26-a088-6eff77776c14)

### Expected behavior
Only 1 test run should be present

### Details

-   Action version: 2.3.0
-   OS, where your action is running (windows, linux): Linux

```
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ArtiomTr/jest-coverage-report-action@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: npm run test:ci
```
### Additional context

In github actions I can see tests are run twice instead of just once.
