### ISSUE TITLE
Show files with reduced coverage is not working

### ISSUE THREAD

**Issue by tibistibi** [ArtiomTr/jest-coverage-report-action#428]
### Describe a bug

When I have setup jest with babel and code all in one directory i get this report:
![image](https://github.com/ArtiomTr/jest-coverage-report-action/assets/1875634/4abff31f-f22f-494a-b34d-4f935c7bcb39)

You see here the `Show files with reduced coverage`. When I move the config files one dir up make it more clean what is my code and what is the config files I get this report:

![image](https://github.com/ArtiomTr/jest-coverage-report-action/assets/1875634/2ff3135a-d62d-4f3f-bdd7-e9f749e79c66)

### Expected behavior

I would like to keep the option to show the files seperately

### Details

-   Action version:
-  run from github action

        ```yml
name: 'coverage location-sf-ods-connector'
on:
    pull_request:
        branches:
            - master
            - main
permissions: write-all
           
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                working-directory: bms/location-sf-ods-connector/lambda
        ```

    </details>

-   <details><summary>Screenshots</summary>
see above
    </details>
