### ISSUE TITLE
Action failing due to Cannot read properties of undefined (reading 'numFailedTests')  error

### ISSUE THREAD

**Issue by Metaphysics0** [ArtiomTr/jest-coverage-report-action#434]
### Describe a bug

the action is failing due to 

```
Error: TypeError: Cannot read properties of undefined (reading 'numFailedTests')
```

this error gets printed very shortly after the generating report log.

I can run the command just fine:
```
npx --ci --json --coverage --testLocationInResults --outputFile=report.json
```
and the report.json gets added to the root directory of my project with the correct fields.

![Screenshot 2025-01-15 at 17 42 18](https://github.com/user-attachments/assets/01c57ea9-08cd-4d5b-9431-770feb785719)

### Expected behavior

Not getting the `numFailedTest` logs

### Details

-   Action version: latest (v2.3.1)
-   OS, where your action is running (windows, linux): linux
-   yaml file here: https://pastebin.com/2KWQAA1B

**Comment by alexmdodge** [comment]
Ran into similar troubles, but it just looks like it's a change in whatever the defacto cached node version was on the GitHub runners. Fixed by just being explicit about what node version should be used:

```yaml
name: 'Jest Coverage Report'
on:
    pull_request:
        branches:
            - master
            - main
   
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v2
              with:
                node-version: 'lts/hydrogen'
                cache: 'npm'
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                test-script: npm run test -- --ci
```
