### ISSUE TITLE
Error: The process '/usr/bin/git' failed with exit code 1

### ISSUE THREAD

**Issue by hinsencamp** [ArtiomTr/jest-coverage-report-action#60]
Hi ArtiomTr, 

very nice action! It does run the tests without problems. However, it doesn't complete any run successfully. Here is the error log:  

```
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.197 s
/usr/bin/git fetch --all --depth=1
13:54:31.022129 git.c:371               trace: built-in: git 'fetch' '--all' '--depth=1'
13:54:31.037398 run-command.c:350       trace: run_command: 'fetch' '--append' 'origin'
Fetching origin
13:54:31.039069 exec_cmd.c:118          trace: exec: 'git' 'fetch' '--append' 'origin'
13:54:31.240141 git.c:371               trace: built-in: git 'fetch' '--append' 'origin'
13:54:31.246548 run-command.c:350       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/microsoft/continuous-service'
* Couldn't find host github.com in the .netrc file; using defaults
*   Trying 140.82.114.3...
* TCP_NODELAY set
* Connected to github.com (140.82.114.3) port 443 (#0)
* found 137 certificates in /etc/ssl/certs/ca-certificates.crt
* found 548 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_ECDSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: github.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: EC/ECDSA
* 	 certificate version: #3
* 	 subject: C=US,ST=California,L=San Francisco,O=GitHub\, Inc.,CN=github.com
* 	 start date: Thu, 25 Mar 2021 00:00:00 GMT
* 	 expire date: Wed, 30 Mar 2022 23:59:59 GMT
* 	 issuer: C=US,O=DigiCert\, Inc.,CN=DigiCert High Assurance TLS Hybrid ECC SHA256 2020 CA1
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /microsoft/continuous-service/info/refs?service=git-upload-pack HTTP/1.1
Host: github.com
User-Agent: git/2.11.0
Accept: */*
Accept-Encoding: gzip
Pragma: no-cache

< HTTP/1.1 401 Authorization Required
< Server: GitHub Babel 2.0
< Content-Type: text/plain
< Content-Security-Policy: default-src 'none'; sandbox
< Content-Length: 21
< www-authenticate: Basic realm="GitHub"
< X-GitHub-Request-Id: 06C0:4B0C:1AA940B:29A18A5:60C75F98
< X-Frame-Options: DENY
< 
* Curl_http_done: called premature == 0
* Connection #0 to host github.com left intact
fatal: could not read Username for 'https://github.com': No such device or address
error: Could not fetch origin
13:54:32.543139 run-command.c:350       trace: run_command: 'gc' '--auto'
13:54:32.543498 exec_cmd.c:118          trace: exec: 'git' 'gc' '--auto'
13:54:32.544993 git.c:371               trace: built-in: git 'gc' '--auto'
Error: The process '/usr/bin/git' failed with exit code 1
```

the actions yml looks like this
```
name: 'code coverage'
on:
    pull_request:
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
            GIT_TRACE: 1
            GIT_CURL_VERBOSE: 1
        steps:
            - uses: actions/checkout@v1
            - uses: artiomtr/jest-coverage-report-action@v1.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  threshold: 80 # value in percents
```

Are you familiar with the issue?

**Comment by ArtiomTr** [comment]
Hello @hinsencamp,

A few more people faced a similar issue (#32). At this moment, bug is fixed in `@master`. Consider using it for now:
```yml
name: 'code coverage'
on:
    pull_request:
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
            GIT_TRACE: 1
            GIT_CURL_VERBOSE: 1
        steps:
            - uses: actions/checkout@v1
#                            specify master version here ↓
            - uses: artiomtr/jest-coverage-report-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  threshold: 80 # value in percents
```

Also, if you use `@master` version, please note that `test_script` option now has new format. It's still not required, so don't worry about it, just saying it if you want to try it 😀. More information [here](https://github.com/ArtiomTr/jest-coverage-report-action/issues/32#issuecomment-855943136).

I hope my answer will help solve your problem!
