### ISSUE TITLE
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

### ISSUE THREAD

**Issue by eleleiva** [ArtiomTr/jest-coverage-report-action#64]
I'm getting this error once the action finishes running the tests.
![Screen Shot 2021-06-16 at 12 04 26](https://user-images.githubusercontent.com/32399007/122244166-09869600-ce9b-11eb-9cc0-6d437d3749ad.png)
This is the action file.
```yaml
name: Coverage report

on: [pull_request]

jobs:
  test:
    name: Test coverage
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      NODE_ENV: test
      DB_NAME: api_test
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      CI_JOB_NUMBER: 1

    container: node:10.0-stretch

    services:
      postgres:
        image: postgres:11.9-alpine
        env:
          POSTGRES_DB: api_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-

      - name: Install dependencies
        run: npm install

      - name: Run migrations
        run: npm run db:migrate

      - name: Run coverage report
        uses: artiomtr/jest-coverage-report-action@master
        with:
          test_script: PORT=5000 NODE_ENV=test jest --runInBand --forceExit --detectOpenHandles --silent --ci --coverage --testLocationInResults --json --outputFile="report.json"
          github_token: ${{ secrets.GITHUB_TOKEN }}

```
