### ISSUE TITLE
Support coverage when push

### ISSUE THREAD

**Issue by bluelovers** [ArtiomTr/jest-coverage-report-action#92]
hope can support coverage when push

**Comment by ArtiomTr** [comment]
Hello @bluelovers,

Sorry, I cannot clearly understand, do you want to trigger this action on every push? For example, when someone pushes to the `master` branch? If so, I would like to ask you, where would you like to see the coverage report comment?

Thank you in advance.

**Comment by bluelovers** [comment]
yes, allow do it when push

and show on latest commit like this
https://github.com/bluelovers/ipfs-web-upload/commit/30e951f7b10d2e0c2c61d310027493dae5716335

or here
https://github.com/bluelovers/ipfs-web-upload/runs/1323740048

**Comment by ArtiomTr** [comment]
Thank you for the explanation! I'll try to implement this as soon as possible

**Comment by ArtiomTr** [comment]
Now, support for `push` event is implemented! You can try it with this configuration:

```yml
name: 'coverage'
on:
    push:
        branches:
            - master
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: artiomtr/jest-coverage-report-action@v2.0-rc.2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  #   threshold: 80 # optional parameter
```
